- src/GlobalVars.res
- src/Utilities/ApiEndpoint.res
- src/Utilities/PaymentHelpers.res
- webpack.common.js
**Problem Description -** Apple Pay Via TrustPay Modal was not opening in case of MWeb intermittently due to the increase in latency in /confirm Api call after CDN changes. ApplePay was throwing user gesture handler error
**Solution -** Removed CDN for confirm call
> fix: HS-158: TrustPay ApplePay user gesture fix for MWeb

- src/Components/DynamicFields.res
- src/Payments/PaymentMethodsRecord.res
**Problem Description -** Fixes for Dynamic Fields
**Solution -** Fixed the following -
1. Dynamic Fields getting passed in confirm body for payment methods where its not enabled
2. Currency, Bank and State value being passed as "" if value is null in payment method list even though value is being rendered in dropdown
> fix: HS-132: Currency Fix and other small Fixes

- src/App.res
- src/orca-loader/Hyper.res
Removed console warning for using link with "as" as  document which wasnt loading up anything  and Batcher error for Recoil occurring inside a useMemo
> fix: HS-174: Removed console warning for using link with document and Batcher error for Recoil

- src/Components/DynamicFields.res
- src/Components/SavedMethods.res
- src/Payments/CardPayment.res
- src/Payments/PaymentMethodsRecord.res
- src/Types/PaymentType.res
**Problem Description -** Required to pass card holder name in confirm call for saved cards
**Solution -** Backend will check whether the stored card has card_holder_name present in the locker. If it is not there, in that scenario it will check whether it is being passed in the confirm body.
Therefore, added check to render card holder name and pass in the confirm call if the following condition pass -
Sample Confirm Request -
```
payment_method_data:
{ card_token:
{ card_holder_name: "Arush Kapoor"
}
}
```
Backend Pr - https://github.com/juspay/hyperswitch/pull/2982
> feat: HS-132: Passing Card Holder Name in Saved Cards Flow

- Hyperswitch-React-Demo-App/package.json
Due to start being called, frontend starts creating a bundle while the server starts to run. The server file is however consumed from the dist folder. So a prebuild is necessary before starting the playground.
> fix:HS-175: Build pre-running concurrently in playground

- Hyperswitch-React-Demo-App/promptScript.js
- README.md
**Problem Description -** OSS setup improvement
**Solution -**
> fix: HS-175: Improved prompts and endpoint fix

- src/Payments/PaymentMethodsRecord.res
**Problem Description -** Removing Dynamic Fields from rendering on SDK when there is already a value for the required_field in PaymentMethodList API
> fix: HS-132: Removing Dynamic Fields from rendering on SDK

- src/Payments/GPay.res
**Problem** : Google pay dynamic fields body going as empty
**fix** : Added a dependency in the Gpay.res
> fix: HS-222: Google pay dynamic fields body going as empty

- src/Components/DynamicFields.res
1. Passing card holder name inside card_token only when it is saved card flow and required_field is `payment_method_data.card_token.card_holder_name`
2. Fixed bug in getNameValue in DynamicFields
> fix: HS-132: Fixed Card Holder Name

- src/Components/Surcharge.res
- src/LocaleString.res
- src/Payments/PaymentMethodsRecord.res
**Problem Description -** Changed Surcharge Flow
**Solution -** Instead of taking surcharge from value inside surcharge object, now it will be taken from surcharge_amount and tax_on_surcharge_amount.
Surcharge Object - 
```
"surcharge_details": {
"surcharge": {
"type": "fixed",
"value": 123,
},
"tax_on_surcharge": {
"percentage": 5.09
},
"display_surcharge_amount": 1.23,
"display_tax_on_surcharge_amount": 0.07,
"display_total_surcharge_amount": 1.30,
"display_final_amount": 66.7
},
```
> fix: HS-148: Changed Flow for Surcharge

- src/orca-loader/Elements.res
**Problem Description -** Custom backend url not working for confirm call, not being picked up from webpack. Passing it in post message to LoaderController
> fix: HS-179: Passing endpoint to loader controller

- src/Types/ApplePayTypes.res
In new flow it is possible for BE to not know what the country code will be. In such scenarios where Client has to send a country, we are setting the country as client's country by default.
> fix: HS-183: ApplePay Payment Request to take client's country in case session sends null

- src/LoaderController.res
- src/orca-loader/Elements.res
- src/orca-loader/Hyper.res
- src/orca-log-catcher/ErrorBoundary.res
- src/orca-log-catcher/OrcaLogger.res
The SDK `loadHyper` and `Hyper` method now accept `options.analytics.metadata` which is a JSON object in case the merchant wishes to send their metadata to their system without code change.
> feat:HS-186: added metadata support for logs

- src/Components/DynamicFields.res
**Problem Description -** areRequiredFieldsValid for postal code was done on whether postal code is empty or not. Changed the check to postalCode.isValid
> fix: HS-132: Fixed areRequiredFieldsValid for postal code

- public/fullscreenIndexTemplate.html
- src/orca-loader/LoaderPaymentElement.res
- webpack.common.js
Currently all the iframes, from the main app to the full screen pop up iframes were using the same assets, i.e., the same index.html file. This led to repeated calls for some assets, and some scripts. This PR includes configuring webpack to use a different index.html template.
> fix: HS-123: created separate iframe for full screen

- src/Components/BillingNamePaymentInput.res
- src/Components/DynamicFields.res
- src/Components/FullNamePaymentInput.res
- src/Utilities/DynamicFieldsUtils.res
**Problem Description -** Add check on the last name for Dynamic Fields
**Solution -** Added check for last name for BillingName and FullName in areRequiredFieldsValid
> fix: HS-180: Added check on last name for Dynamic Fields

- src/LoaderController.res
- src/orca-loader/Elements.res
- src/orca-loader/Hyper.res
**Problem Description -** New Elements File without the PreMountLoader
> fix: HS-166: New Elements fle without PreMountLoader

- src/Payments/CardPayment.res
- src/Types/PaymentType.res
Hide Save Card Details Checkbox until CustomerPaymentMethodsList responds with is_guest_customer false to prevent payment attempt with setup_future_usage: "on_session" when customer_id is actually null
fixes #183
> fix(animatedcheckbox): Save Card Details checkbox changes

- src/Components/PayNowButton.res
- src/orca-loader/Hyper.res
feat(PayNowButton): handling onClick of PayNowButton when sdkHandleConfirmPayment is set to true
> feat(PayNowButton): handling onClick of PayNowButton when sdkHandleConfirmPayment is set to true

- src/Utilities/PaymentHelpers.res
In case of no response from server, or a timed out request, try to retrieve the payment intent to know the true payment status
> fix(intentCall): handling no response on confirm

- src/Payments/CardPayment.res
customer_acceptance - not to append in the case for guest customer and payment type is normal
> fix: card payment customer_acceptance

- src/Components/DynamicFields.res
- src/Components/SavedCardItem.res
- src/Components/SavedMethods.res
- src/PaymentElement.res
- src/Types/PaymentType.res
1. SDK getting stuck on Saved Payment Method screen when no customer was provided
2. Card Holder Name field was being asked by Dynamic Fields even when card holder name was present for that specific saved card
> fix: saved Payment Method stuck in loading state and Card Holder Name for every saved card

- src/Payments/ApplePay.res
- src/Utilities/DynamicFieldsUtils.res
- src/orca-loader/Elements.res
1. ApplePay Dynamic Fields Error handling failing. The merchant button getting stuck in Processing...
2. Dynamic Fields areRequiredFieldsValid failing because of postal code validation in scenario (found by not passing country in `/create-payment-intent` call)
> fix: applePay Dynamic Fields Error Handling and Dynamic Fields PostalCode Error

- src/Components/DynamicFields.res
- src/Payments/PaymentMethodsRecord.res
- src/Payments/PaymentMethodsWrapper.res
Giropay Dynamic fields added and tested for Giropay, Sofort, EPS and iDeal.
Tested all the payment methods via PM testing via TrustPay.
> feat: giropay dynamic fields added

- src/Payments/GPay.res
- src/Utilities/PaymentHelpers.res
- src/orca-loader/Elements.res
1. Added Background Loader once TrustPay GooglePay button is clicked.
2. Added polling and timeout for TrustPay GooglePay
Tested transactions via TrustPay GooglePay
> fix: added Loader and Error Handling for TrustPay GooglePay

- src/LoaderController.res
Fix for APP_RENDERED event latency calculation
By observing latency value in the logs containing the APP_RENDERED event_name
> fix: app rendered event latency calculation

- .github/workflows/pr-label-removal.yml
Removing existing labels from the PR and adding closed label in the end when the PR will be merged.
Merge a PR to main with existing labels it will remove them and add a closed label.
> feat: add GitHub Actions workflow for removing labels from PRs

- .eslintrc.json
- .github/workflows/CI-Action.yml
> fix: build failing issue because of lower node version

- Hyperswitch-React-Demo-App/webpack.dev.js
- src/orca-loader/Hyper.res
- webpack.dev.js
Prefetching assets will cache the resources in prefetch cache and will be available for subsiquient pages, iframes or diff domain which increases the performance in loading time of SDK
> fix(hyper.res): prefetch assets instead of preload

- src/PaymentElement.res
- src/Utilities/PaymentHelpers.res
For users it looked like Promise is being unresolved as the button was being stuck in the loading state.
-  Ready promise was not getting created 
-  Ready message was not being sent to create the promise (missed one edge case) 
-  Return the appropriate msg and resolve the promise in the case of empty PML instead of () empty function
-  Send Ready msg even in the case of Semiloaded -> LoadError state cuz this will have card form by default. 
-  Do not make /confirm call if the PML response is empty. Resolve the promise and throw a warning on console
> fix: (paymenthelpers, paymentelement) promise being unresolved 

- src/PaymentElement.res
- src/Utilities/PaymentHelpers.res
Promise being unresolved 
- if any of the confirm params are invalid 
- if there is a runtime error while handling the response from /confirm call
> fix: promise unresolved type error

- src/Payments/CardPayment.res
Whenever mandate_data is been passed in the flow the checkbox need not to be shown as customer_acceptance will always be sent.
Pass mandate_data in payments. and customer_acceptance will be passed and checkbox will not be visible.
> fix: mandate data pass hide checkbox

- webpack.common.js
- webpack.dev.js
Added envLoggingUrl to consume logging url from env in webpack if available
> fix: Added envLoggingUrl in webpack

- src/Payments/ApplePay.res
- src/Payments/GPay.res
- src/orca-loader/Elements.res
move Trustpay applepay event listeners outside of handleSessionTokensLoaded event listener
> fix: move applepay thirdparty event listeners outside

- src/Payments/PaymentMethodsWrapper.res
- src/Utilities/PaymentBody.res
Test the confirm body for the following payment methods -
- affirm
- mobile_pay
- ali_pay (Both redirection and QR)
- we_chat_pay (Both redirection and QR)
- online_banking_finland
- walley
- pay_bright
- twint
- vipps
- dana
- go_pay
- kakao_pay
- gcash
- momo
- touch_n_go
- bizum
- alma
- atome
- card_redirect
- open_banking_uk
- pix
- local_bank_transfer
> refactor(paymentbody): refactored Payment Body

- src/Components/SavedCardItem.res
- src/Types/PaymentType.res
There was no prop for hiding the expired saved payment methods now we can hide expired saved payment methods via passing this prop in PaymentElementOptions. 
```js
let options = {
...,
"hideExpiredPaymentMethods": true,
}
```
Via passing hideExpiredPaymentMethods in options it will hide the expied cards.
> feat: hideExpiredPaymentMethods prop added

- src/Components/DynamicFields.res
- src/Payment.res
- src/Payments/CardPayment.res
- src/Payments/PaymentMethodsRecord.res
- src/Utilities/DynamicFieldsUtils.res
- src/Utilities/PaymentBody.res
Moved Card Number, Card CVC and Card Expiry Fields to Dynamic Fields
1. Tested Saved Cards Flow
2. Tested Cards With Dynamic Fields
3. Tested Cards in fallback scenarios
> refactor: moved Card Number, Cvc and Expiry to Dynamic Fields for Card Payment method

- src/Components/DynamicFields.res
- src/Utilities/DynamicFieldsUtils.res
Combined Dynamic Fields for credit and debit
Even if Dynamic Fields are only coming for credit, the fields should still be visible
> fix: combined Dynamic Fields for credit and debit

- src/Components/DynamicFields.res
- src/Payments/PaymentMethodsRecord.res
- src/Utilities/DynamicFieldsUtils.res
fixed Saveds Card Confirm Body Sending card details
Test Saved Cards Flow and Non Saved Card Flow
> fix: fixed Saveds Card Confirm Body Sending card details

- package.json
- src/CardUtils.res
- src/LocaleStrings/ArabicLocale.res
- src/LocaleStrings/CatalanLocale.res
- src/LocaleStrings/DeutschLocale.res
- src/LocaleStrings/DutchLocale.res
- src/LocaleStrings/EnglishGBLocale.res
- src/LocaleStrings/EnglishLocale.res
- src/LocaleStrings/FrenchBelgiumLocale.res
- src/LocaleStrings/FrenchLocale.res
- src/LocaleStrings/HebrewLocale.res
- src/LocaleStrings/ItalianLocale.res
- src/LocaleStrings/JapaneseLocale.res
- src/LocaleStrings/LocaleStringTypes.res
- src/LocaleStrings/PolishLocale.res
- src/LocaleStrings/PortugueseLocale.res
- src/LocaleStrings/RussianLocale.res
- src/LocaleStrings/SpanishLocale.res
- src/LocaleStrings/SwedishLocale.res
- src/Payments/CardPayment.res
- src/Utilities/Utils.res
Added error for the card networks which are not configured via merchant.
tested via account which has not configured one network like Rupay and tested with that flow. the error was being thrown and confirm call didn't happen.
> fix: card brand configuration error added

- src/Components/PayNowButton.res
- src/Payments/GPay.res
Pay now button was not enabling for req fields fix
> fix: paynow button fix for required fields

- src/Utilities/PaymentHelpers.res
Added display_voucher_information again. Causing issue for boleto
Tested Boleto Pay end to end flow. Modal should open post /confirm
> fix: added display_voucher_information again

- src/Utilities/PaymentHelpers.res
Added content length in logs
Via checking the request headers content-length
> feat: added content length

- src/Payments/PreMountLoader.res
- src/orca-loader/Elements.res
Not unmounting preMountLoader iframe after api calls
> fix: do not unmount preMountLoader iframe

- src/Components/DynamicFields.res
- src/PaymentElement.res
- src/PaymentElementRenderer.res
- src/Payments/ApplePay.res
- src/Payments/ApplePay.resi
- src/Payments/ApplePayLazy.res
- src/Payments/GPay.res
- src/Payments/GPay.resi
- src/Payments/GPayLazy.res
- src/Payments/PayPal.res
- src/Payments/PaymentMethodsRecord.res
- src/Payments/PaymentRequestButtonElement.res
- src/Payments/PaypalSDK.res
- src/Payments/PaypalSDK.resi
- src/Payments/PaypalSDKLazy.res
- src/RenderPaymentMethods.res
- src/Types/ApplePayTypes.res
- src/Types/GooglePayType.res
- src/Types/PaypalSDKTypes.res
- src/Types/SessionsType.res
- src/Utilities/DynamicFieldsUtils.res
- src/Utilities/PaymentUtils.res
- src/Utilities/Utils.res
- src/WalletElement.res
- src/orca-loader/Elements.res
Added Support to collect billing and shipping details from ApplePay, GooglePay and Paypal instead of the SDK
https://docs.google.com/document/d/1yvMroZvHGQQrPwMg5WvjEd7kxRFWslpJzzdFsSQTXUk/edit?usp=sharing
> feat: address collection for one click widgets

- src/CardTheme.res
- src/LoaderController.res
Locale string will now be imported dynamically
Via checking the network tab whenever that chunk is required then only that locale file is being imported.
> refactor: locale string refactoring

- src/Components/SavedCardItem.res
- src/Components/SavedMethods.res
- src/Payment.res
- src/PaymentElement.res
- src/Types/RecoilAtomTypes.res
- src/Utilities/RecoilAtoms.res
Payment Token type change form tuple to object for better clarification and understanding
Code compile
> refactor: change payment token type from tuple to object

- src/orca-loader/Elements.res
feat: isolate paymentElementCreate message from preMountLoader promise
postMessage to not wait for premountloader promise to resolve
> feat: isolate paymentElementCreate message

- src/Components/PayNowButton.res
- src/Utilities/PaymentBody.res
Fix for redirect as it was been passed in wrong place
Via passing redirect = always and checking the redirection
> fix: sdk button redirect issue

- src/Components/PayNowButton.res
Loader was not getting stopped in case of failed payments
Via making a failed and a succesfull payment
> fix: sdk button loader issue

- src/orca-loader/Elements.res
ApplePay Event Handler, picking up incorrect event
Tested ApplePay flow and payment got succeeded
> fix: fixed ApplePay Event Handler

- src/Components/SavedMethods.res
- src/Payments/CardPayment.res
`displaySavedPaymentMethodsCheckbox` based upon this prop hiding terms also.
Via passing the prop and checking it.
> fix: hide terms based upon prop

- src/orca-loader/Elements.res
Payment loader screen when polling
> fix: 3ds netcetra paymentloader

- src/Payments/ApplePay.res
- src/Types/PaymentModeType.res
Added border apple pay border outline
Via UI
> fix: apple-pay outline

- src/PaymentElement.res
- src/Payments/CardPayment.res
- src/Payments/PaymentMethodsRecord.res
- src/Utilities/PaymentUtils.res
Removed Klarna Fallback in case of sessions call fail based on payment experience
1. When payment experience is invoke_sdk_client
- Sessions Call contains Klarna - Klarna SDK should be rendered
- Sessions Call does not contain Klarna - Klarna SDK should not be rendered
2. When payment experience is redirect_to_url
- Sessions Call contains Klarna - Klarna Redirect should be rendered (in tabs)
- Sessions Call does not contain Klarna - Klarna Redirect should be rendered (in tabs)
3. When payment experience is invoke_sdk_client and redirect_to_url
- Sessions Call contains Klarna - Klarna SDK should be rendered
- Sessions Call does not contain Klarna - Klarna Redirect should be rendered (in tabs)
> fix: removed fallback in case of sessions call fail based on payment experience

- src/LoaderController.res
- src/Window.res
- src/orca-loader/Hyper.res
Logging href without including url search params
> feat: log href without including search params

- src/Utilities/DynamicFieldsUtils.res
Country Code Fix for ApplePay
Billing and Shipping countryCode coming from Apple are transformed to UpperCase before passing to Backend in the confirmCall
> fix: transforming billing and shipping country code to touppercase for applepay

- package.json
- src/Payments/GPay.res
- src/Utilities/Utils.res
- src/orca-loader/PaymentSessionMethods.res
Warnings removed and headers added
> fix: headers update & warnings removed

- webpack.common.js
> fix: added Env to disable sentry by default

- src/Components/SavedMethods.res
- src/Payment.res
- src/Payments/ACHBankDebit.res
- src/Payments/ACHBankTransfer.res
- src/Payments/ApplePay.res
- src/Payments/BacsBankDebit.res
- src/Payments/BacsBankTransfer.res
- src/Payments/BecsBankDebit.res
- src/Payments/Boleto.res
- src/Payments/CardPayment.res
- src/Payments/GPay.res
- src/Payments/KlarnaPayment.res
- src/Payments/KlarnaSDK.res
- src/Payments/PayPal.res
- src/Payments/PaymentMethodsWrapper.res
- src/Payments/PaypalSDK.res
- src/Payments/PaypalSDKHelpers.res
- src/Payments/SepaBankDebit.res
- src/Payments/SepaBankTransfer.res
- src/Utilities/ApplePayHelpers.res
- src/Utilities/GooglePayHelpers.res
- src/Utilities/PaymentHelpers.res
Manual Retries not working - intent function was a closure of the `usePaymentIntent` hook 
Hence it was not getting the updated value
> fix: manual retries

- src/Utilities/ApplePayHelpers.res
- src/Utilities/GooglePayHelpers.res
googlePay and applePay billing details not being passed in confirm call for saved methods
Billing Details should be passed in the confirm body for ApplePay and GooglePay in Saved Payment Methods Flow
> fix: googlePay and applePay billing details not being passed in confirm call for saved methods

- src/PaymentElement.res
- src/Utilities/PaymentUtils.res
Saved PM - Wallets were not coming on Top.
> fix: wallets on top for saved cards flow

- webpack.common.js
- webpack.dev.js
Integ API Change requested by BE
Via passing sdkEnv = local via package-lock.json
> fix: integ api change

- src/Components/SavedMethods.res
- src/Types/PaymentType.res
- src/orca-loader/PaymentSessionMethods.res
Passing customer acceptance in the confirm body for the saved payment methods if recurring_enabled is false in the customers payment method list
If recurring_enabled is false, pass customer_acceptance in the confirm body. If recurring_enabled is true, customer_acceptance should not be passed in the confirm body.
> fix: passing customer acceptance if recurring_enabled is false in saved methods list

- src/Payments/DateOfBirth.res
- src/Utilities/DynamicFieldsUtils.res
- src/Utilities/PaymentHelpers.res
- src/Utilities/RecoilAtoms.res
- src/Utilities/Utils.res
- src/libraries/DatePicker.res
- src/orca-log-catcher/OrcaLogger.res
Added null values in Date of Birth so Placeholder text can be shown.
Added validations for handling error that it should be > 18 years
Via opening Mifinity
> fix: date of birth validations

- public/icons/orca.svg
- src/Components/DynamicFields.res
- src/Components/VpaIdPaymentInput.res
- src/LocaleStrings/ArabicLocale.res
- src/LocaleStrings/CatalanLocale.res
- src/LocaleStrings/DeutschLocale.res
- src/LocaleStrings/DutchLocale.res
- src/LocaleStrings/EnglishGBLocale.res
- src/LocaleStrings/EnglishLocale.res
- src/LocaleStrings/FrenchBelgiumLocale.res
- src/LocaleStrings/FrenchLocale.res
- src/LocaleStrings/HebrewLocale.res
- src/LocaleStrings/ItalianLocale.res
- src/LocaleStrings/JapaneseLocale.res
- src/LocaleStrings/LocaleStringTypes.res
- src/LocaleStrings/PolishLocale.res
- src/LocaleStrings/PortugueseLocale.res
- src/LocaleStrings/RussianLocale.res
- src/LocaleStrings/SpanishLocale.res
- src/LocaleStrings/SwedishLocale.res
- src/Payments/PaymentMethodsRecord.res
- src/Utilities/DynamicFieldsUtils.res
- src/Utilities/RecoilAtoms.res
- src/Utilities/Utils.res
Added upi collect payment method type
Payment Method List Response - 
```
{
"redirect_url": "https://google.com/success",
"currency": "INR",
"payment_methods": [
{
"payment_method": "upi",
"payment_method_types": [
{
"payment_method_type": "upi_collect",
"payment_experience": [
{
"payment_experience_type": "redirect_to_url",
"eligible_connectors": [
"razorpay"
]
}
],
"card_networks": null,
"bank_names": null,
"bank_debits": null,
"bank_transfers": null,
"required_fields": {
"payment_method_data.upi.upi_collect.vpa_id": {
"required_field": "payment_method_data.upi.upi_collect.vpa_id",
"display_name": "vpa_id",
"field_type": "user_vpa_id",
"value": null
}
},
"surcharge_details": null,
"pm_auth_connector": null
}
]
}
],
"mandate_payment": null,
"merchant_name": "NewAge Retailer", …
```
> feat: added upi collect payment method type

- src/App.res
- src/CardTheme.res
- src/Components/DynamicFields.res
- src/LoaderController.res
- src/Payments/CardPayment.res
- src/Payments/PaymentMethodsRecord.res
- src/Types/CardThemeType.res
- src/Utilities/DynamicFieldsUtils.res
- src/Window.res
added language preference for mifinity
if the language passed by merchant is supported by mifinity then we pass it as same, else if the language passed is auto then we take language from browser, else we pass "en".
tested by firstly passing supported language locale , the sdk was rendered in the provided language, then passed the locale as "auto", the sdk rendered in browser specified language, then passed an unsupported and empty locale, in this case the english language was shown.
> feat: language preference for mifinity added

- src/CollectWidget.res
This PR fixes the logic of updating `availablePaymentMethodTypesOrdered` which is used for rendering the available PMTs in tab view.
Locally
> fix(payout): handle tab order updates

- src/App.res
- src/Payments/PreMountLoader.res
- src/Utilities/PaymentHelpers.res
- src/Utilities/Utils.res
- src/orca-loader/Elements.res
passing X-Merchant-Domain in the headers for Sessions Call
> feat: passing X-Merchant-Domain in the headers for Sessions Call

- src/orca-loader/Elements.res
passing initiativeContext to TrustPay ApplePay
Went inside TrustPay's script to verify intitativeContext is being passed
> fix: passing initiativeContext to TrustPay ApplePay

- src/orca-loader/Elements.res
Reverts juspay/hyperswitch-web#519
> revert: passing initiativeContext to TrustPay ApplePay

- src/PaymentElement.res
- src/Payments/ApplePay.res
- src/Payments/ApplePay.resi
- src/Payments/GPay.res
- src/Payments/GPay.resi
- src/Payments/PaymentMethodsRecord.res
- src/Payments/PaymentRequestButtonElement.res
- src/Utilities/ApplePayHelpers.res
- src/Utilities/DynamicFieldsUtils.res
- src/Utilities/GooglePayHelpers.res
- src/Utilities/PaymentUtils.res
Added Support for `collecting_billing_details_from_wallets` to decide whether to collect billing details for wallets (ApplePay and GooglePay) from SDK or from the Wallet SDK.
case `collecting_billing_details_from_wallets` true:
1. ApplePay and GooglePay billing details should be collected from Wallet SDK and passed correctly in the confirm body
case `collecting_billing_details_from_wallets` false:
1. ApplePay and GooglePay billing details should be collected from SDK instead of the Wallet and passed correctly in the confirm body
2. If all details are prefilled, do not put ApplePay and GooglePay in the tabs
3. ApplePay should not be visible in Chrome
4. If you cancel ApplePay or GooglePay error message should be sent to the merchant
> feat: added support for collecting_billing_details_from_wallets

- src/PaymentMethodCollectElement.res
This PR removes error code and message from the status UI for payout widget. This is being done as a part of localisation for now. Once localisation support is added in our APIs, this change will be reverted (or not, let's see).
Locally.
> refactor(payout): remove error code and error message from status page

- src/Payments/PaymentMethodsRecord.res
- src/Utilities/DynamicFieldsUtils.res
- src/Utilities/PaymentBody.res
- src/Utilities/Utils.res
Fixed structure of billing details in payment body based on backend requirement [https://github.com/juspay/hyperswitch-cloud/issues/4144](https://github.com/juspay/hyperswitch-cloud/issues/4144)
Tested the  confirm payload for the following payment methods -
1. ach_bank_debit
2. sepa_bank_debit
3. bacs_bank_debit
4. becs_bank_debit
5. ach_bank_transfer
6. bacs_bank_transfer
7. sepa_bank_transfer
8. przelewy24
9. multibanco_bank_transfer
> fix: fixed structure of billing details in payment body

- Hyperswitch-React-Demo-App/src/CheckoutForm.js
- src/orca-loader/Hyper.res
reverted changes for hyper.res from previous pr
by code compilation and rendering the SDK and checking confirm call
> fix: revert changes for hyper.res

- src/Components/DropdownField.res
- src/Components/DynamicFields.res
Added classnames for billing section and billing details text for customization purposes.
By passing the classes in Payment.js and rendering the SDK, checking whether correct styles get applied or not
> refactor: added classes for billing section and billing details text

- Dockerfile
Dockerize the hyperswitch-web which will serve the HyperLoader.js at 9050 port.
via running these commands.
1.  docker build -t hyperswitch-web .
2. docker run -p 9050:9050 hyperswitch-web
3. hit the url - http://localhost:9050/HyperLoader.js (the url will be accessible)
> feat: dockerize the hyperswitch-web

- src/Payments/GPay.res
- src/RenderPaymentMethods.res
fixed the top border of google pay button
Before:-
After:-
by rendering the sdk and checking the UI of google pay button
> fix: google pay button border

- .github/workflows/pr-title-spell-check.yml
- src/Components/PayNowButton.res
- src/Hooks/UtilityHooks.res
- src/TabCard.res
- src/Types/PaymentType.res
- src/Utilities/RecoilAtoms.res
SDK pay now button will always remain enabled.
rendering the SDK and checking whether SDK pay now button is enabled for all payment methods or not.
> refactor: sdk pay now always enabled

- src/CollectWidget.res
- src/PaymentMethodCollectElement.res
(cherry picked from commit af289420c2aae6bfcd2d3112e763f9e57f8eef7d)
Fixes tab selection update, minor UI improvements.
Locally
> fix(payout): dropdown for selecting payment methods, UI updates

- src/App.res
- src/Components/SavedPaymentManagement.res
- src/LoaderController.res
- src/PaymentMethodCollectElement.res
- src/Payments/PlaidSDKIframe.res
- src/Payments/PreMountLoader.res
- src/Payments/QRCodeDisplay.res
- src/Utilities/ApiEndpoint.res
- src/Utilities/PaymentHelpers.res
- src/Utilities/RecoilAtoms.res
- src/orca-loader/Elements.res
- src/orca-loader/PaymentMethodsManagementElements.res
- src/orca-loader/PaymentSession.res
- src/orca-loader/PaymentSessionMethods.res
added support for customPodValue instead of switchToCustomPod
`x-feature` value, if passed in options should be present in the request header for all the api calls made from the SDK.
> fix: added support for customPodUri instead of switchToCustomPod

- src/BrutalTheme.res
- src/CharcoalTheme.res
- src/Components/Accordion.res
- src/Components/AccordionContainer.res
- src/DefaultTheme.res
- src/MidnightTheme.res
- src/SoftTheme.res
Added customization support for padding inside .AccordionItem rule
[Issue Link](https://github.com/orgs/juspay/projects/22/views/2?pane=issue&itemId=76559442)
Before - 
After -
The card tab will look the same since the value of padding is same. There is slight change in the loader icon for Accordion
> fix: added customization for padding inside accordion item rule

- src/orca-loader/Elements.res
added loader for netecetera when openurl_if_required is sent post otp submission
Modal will close and fullscreen loader should open in case the post message from backend is `openurl_if_required`.
> fix: added loader for netecetera when openurl_if_required is sent post otp submission

- src/Hooks/UtilityHooks.res
- src/ThreeDSAuth.res
Post message events being sent on the top level were not working in scenarios where the SDK along with HyperLoader and event listeners is mounted inside an iframe.
Added support to listen to such events in the parent iframe and send these post messages on level above instead of directly sending it to the top parent.
https://github.com/user-attachments/assets/be9e7982-e210-4d0e-ae13-5aaa5573ed4d
> fix: added support to send post messages to parent iframe

- Hyperswitch-React-Demo-App/server.js
- src/Utilities/Utils.res
- src/orca-loader/Elements.res
Changed Post message being sent to parent to current
Tested netcetera flow(challenge and frictionless) for both where our SDK is opening inside and iframe and on the top level with `capture_method` as `manual` and `redirect` as `if_required`
> fix: changed post message from parent window to current window

- webpack.common.js
Added integ env check in webpack
Need to test it in integ
> fix: integ env in webpack

- src/CardUtils.res
- src/GlobalVars.res
- src/Payment.res
- src/Utilities/PaymentUtils.res
- src/Utilities/Utils.res
added wild card check in case of unsupported cards.
by entering an unsupported card which is a wild card
> fix: added wild cards support

- src/Payments/DateOfBirth.res
- src/Utilities/DynamicFieldsUtils.res
Added logs for Date of birth input field
By rendering the Date of birth input field for a payment method and then checking whether logs are being sent or not
> refactor: date of birth log added

- src/CollectWidget.res
- src/FormViewTabs.res
- src/PaymentMethodCollectElement.res
- src/Types/PaymentMethodCollectTypes.res
- src/Utilities/PaymentMethodCollectUtils.res
make SEPA BIC optional
populate default requiredFields in case backend returns an empty response
This PR contains below fixes
- update form value on change in dropdown fields (country code not updating)
- use default fields for payment method data form in case backend returns an empty response
- add validation for IBAN and make BIC optional
Locally.
[Screencast from 16-09-24 03:30:14 PM IST.webm](https://github.com/user-attachments/assets/2573117f-58ab-4710-997e-69923e7645bf)
> fix(payout): on change handler for dropdown

- src/Utilities/ApplePayHelpers.res
- src/Utilities/TaxCalculation.res
Dynamic Tax response type changed from integer to float due to compatibility issues.
Sample tax api response:
`{
"payment_id": "pay_D1KwskbRrHs2wZcXzi6w",
"net_amount": 4190,
"order_tax_amount": 190,
"shipping_cost": 1000,
"display_amount": {
"net_amount": "41.90",
"order_tax_amount": "1.90",
"shipping_cost": "10.00"
}
}`
> fix: dynamic tax calculation fix

- src/PaymentElementRenderer.res
- src/PaymentElementRenderer.resi
- src/PaymentElementRendererLazy.res
- src/RenderPaymentMethods.res
Chunk loading issue debug phase - 1. Removed lazy from payment element renderer and try to debug and check logs once again.
Via logs we tested this.
```
{
"error": {
"message": "Loading chunk 872 failed.\n(missing: https://checkout.hyperswitch.io/0.84.14/v0/872.js)",
"name": "ChunkLoadError",
"type": "missing",
"request": "https://checkout.hyperswitch.io/0.84.14/v0/872.js",
"cause": {
"name": "React ErrorBoundary ChunkLoadError"
}
},
"componentStack": "\n at Lazy\n at Suspense\n at ErrorBoundary (https://checkout.hyperswitch.io/0.84.14/v0/app.js:2:356052)\n at make (https://checkout.hyperswitch.io/0.84.14/v0/app.js:2:362824)\n at make (https://checkout.hyperswitch.io/0.84.14/v0/app.js:2:378246)\n at div\n at div\n at div\n at RenderPaymentMethods_bs_make …
```
> fix: chunk loading issue - 1

- src/Utilities/ApplePayHelpers.res
- src/Utilities/TaxCalculation.res
- src/Utilities/Utils.res
Invalid shipping address and taxjar api failing case handle in apple pay
Invalid shipping address and taxjar api failing case handle in apple pay. Aborting the apple pay session for invalid address selection and taxjar api failing.
> fix: Invalid shipping address and taxjar api failing case handle in apple pay

- src/PaymentElement.res
Added Suspense and Error Boundary for ApplePay and GooglePay
Test ApplePay and GooglePay in tabs flow
> fix: added suspense and error boundary for apple pay and google pay in tabs

- src/orca-loader/Elements.res
- src/orca-loader/Hyper.res
Added Support for RedirectUrl for Netcetera Flow with SDK Button
Test both frictionless and challenge flow for netcetera via SDK button. (The redirected url should have client_secret and status appended to it)
> fix: added support for redirectUrl for netcetera flow

- src/Components/DynamicFields.res
- src/Components/SavedMethods.res
- src/Payments/CardPayment.res
Added style fixes required by a certain merchant.
Locally adding styles.
> fix: styling issues

- src/Components/SaveDetailsCheckbox.res
- src/Components/Terms.res
- src/Types/PaymentType.res
Added customMessageForCardTerms for providing custom message support for card Terms
via passing from the `Checkform.js`
```js
const options = {
...,
customMessageForCardTerms: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla consequat libero nec bibendum tempor.",
};
```
> feat: customMessageForCardTerms prop added

- src/Payments/PaypalSDKHelpers.res
- src/Types/PaymentType.res
- src/Types/PaypalSDKTypes.res
- src/Utilities/DynamicFieldsUtils.res
- src/Utilities/Utils.res
Pass email and phone number to confirm call
Passing email address and phone number for paypal in confirm call, for apple pay and klarna it is already getting passed.
> feat: pass email and phone number to confirm call

- src/PaymentElement.res
- src/Utilities/PaymentUtils.res
1. GooglePay was not appearing in tabs even when session_token is present.
2. ApplePay appearing in tabs when session_token in not present
1. Test GooglePay and ApplePay in tabs based on session_token. (also try by adding throttling)
2. Sanity is also required
> fix: added fix for google_pay and apple_pay

- src/Components/SaveDetailsCheckbox.res
- src/Components/SavedMethods.res
Customer Acceptance was not getting passed. Added a check and condition for passing customer acceptance.
Via checking and unchecking the Saved Card Checkbox
> fix: customer-acceptance for saved pm

- src/orca-loader/Hyper.res
SDK was redirecting everytime in case of SDK pay now button was clicked, fixed it by adding a condition of only redirect when submit successfull is true.
by trying to click on pay now without providing all fields
> fix: sdk pay now redirect fix

- src/Types/ApplePayTypes.res
- src/orca-loader/PaymentSessionMethods.res
We were not passing `session_token_data` to **startApplePaySession**, `payment_request_data` was being passed
Sample response
```
{
"session_token_data": {
"epoch_timestamp": "PLACEHOLDER_TIMESTAMP",
"expires_at": "PLACEHOLDER_EXPIRATION",
"merchant_session_identifier": "PLACEHOLDER_MERCHANT_SESSION_ID",
"nonce": "PLACEHOLDER_NONCE",
"merchant_identifier": "PLACEHOLDER_MERCHANT_ID",
"domain_name": "PLACEHOLDER_DOMAIN",
"display_name": "PLACEHOLDER_DISPLAY_NAME",
"signature": "PLACEHOLDER_SIGNATURE"
},
"payment_request_data": {
"country_code": "PLACEHOLDER_COUNTRY_CODE",
"currency_code": "PLACEHOLDER_CURRENCY_CODE",
"total": {
"label": "PLACEHOLDER_LABEL",
"type": "PLACEHOLDER_TYPE",
"amount": "PLACEHOLDER_AMOUNT"
},
"merchant_capabilities": [
"PLACEHOLDER_CAPABILITY"
], …
```
> fix: fixed applePay for headless fow

- src/Utilities/PaymentHelpers.res
Closed loader if there is any before executing the merchant callback
By passing a onPaymentComplete callback and checking if the loader is getting closed or not
> fix: closed loader before calling merchant callback

- src/Components/DynamicFields.res
When billing details are rendered then an extra horizontal scroll bar was observed in safari.
Before:
https://github.com/user-attachments/assets/13c99d79-3b8f-44c7-8217-a9e07a87e2dc
After:
https://github.com/user-attachments/assets/8f7a1a98-c4d6-4ffc-89b9-0d2c6fe6f587
Tested via rendering the SDK in safari
> fix: extra scroll in safari

- src/Components/DropdownField.res
- src/Components/PaymentDropDownField.res
When billing details are rendered then text inside the dropdown is overflowing 
Before:
After:
Tested via rendering the SDK in safari and chrome
> fix: add text overflow with ellipsis in dropdown

- src/LoaderController.res
- src/Types/ApplePayTypes.res
- src/Utilities/ApplePayHelpers.res
- src/Utilities/PaymentHelpers.res
- src/Utilities/Utils.res
- src/Window.res
- src/orca-loader/Elements.res
- src/orca-loader/Hyper.res
- src/orca-loader/PaymentSessionMethods.res
Implemented support for initiating an ApplePay session within an iframe, provided that a HyperLoader script is present at the parent level.
> feat: added apple pay support inside an iframe

- src/index.css
Contact/Password icon appears in the input field when using safari browser.
So, to remove those icons I followed this reference -> https://stackoverflow.com/questions/38663578/how-to-hide-autofill-safari-icon-in-input-field
Before:
text input (using `type_="text"`)
password input (using `type_="password"`)
After:
Tested via rendering the SDK in firefox ,safari and chrome
> fix: remove contact and password icon in safari

- src/ThreeDSAuth.res
- src/ThreeDSMethod.res
- src/index.css
- src/orca-loader/Elements.res
- src/orca-loader/LoaderPaymentElement.res
- src/orca-loader/PaymentMethodsManagementElements.res
When clicking on the button, or active iframe in Firefox, a blue border appears. This is caused by default browser behavior.
To resolve this, I have made every tags outline none when they are in focus and active state. The CSS change is applied specifically for Firefox to avoid affecting other browsers. For iframe, I have added inline styles as other ways of adding styles were not working.
Before:
https://github.com/user-attachments/assets/7ce64e1d-fde3-4b94-b209-e4ba470ceaca
After:
https://github.com/user-attachments/assets/7fc70ed4-838f-4c27-8f22-0049f60182aa
Tested via rendering the SDK in firefox, safari and chrome. (Also used ngrok for temporary deployment)
> fix: remove blue border of iframe in firefox

- src/Payments/PaymentMethodsRecord.res
Added dynamic fields support for affirm
Tested via not passing email to a new customer_id and checking whether it is getting rendered through dynamic fields or not.
Tested via passing all the values and checking no field should be rendered.
> feat: add dynamic fields support for affirm

- src/Payments/BacsBankTransfer.res
- src/Utilities/DynamicFieldsUtils.res
- src/Utilities/PaymentBody.res
- src/Utilities/Utils.res
Added dynamic fields support for Bacs bank transfer
> chore: added dynamic fields support for bacs bank transfer

- src/CardUtils.res
- src/Payment.res
replaced if statements with switch in cardError code.
By compiling code and also via rendering the SDK in chrome.
> refactor: replace if statements with switch in cardError code

- src/CardUtils.res
- src/LoaderController.res
- src/Payments/PaymentRequestButtonElement.res
- src/Payments/PazeButton.res
- src/Payments/PazeWallet.res
- src/RenderPaymentMethods.res
- src/Types/ApplePayTypes.res
- src/Types/CardThemeType.res
- src/Types/PaymentType.res
- src/Utilities/Utils.res
- src/hyper-loader/Elements.res
Paze Express Checkout Element Added.
Working properly. Tested.
https://github.com/user-attachments/assets/067309cb-eb57-48e1-b289-c9c820862a1d
Via rendering locally
> feat: express checkout for paze

- src/Utilities/Utils.res
- src/hyper-loader/Elements.res
So need to fix one issue in the express checkout. It was throwing this error when I tried to combine two functions - `handleApplePayIframePostMessage` & `handlePazeIframePostMessage`
```
caml_option.js:24 Uncaught SecurityError: An attempt was made to break through the security policy of the user agent. at Module.handlePazeIframePostMessage (VM26169 Utils.bs.js:1367:170) at onPazeCallback (Elements.bs.js:118:7)
```
Reverted back and made some changes started working.
> fix: paze express checkout for multiple iframe

- src/Utilities/PaymentHelpers.res
Stringified the json body and headers for block confirm call
by blocking the confirm call and checking logs
> refactor: stringify json for block confirm body and headers

- src/Components/FullNamePaymentInput.res
- src/LocaleStrings/ArabicLocale.res
- src/LocaleStrings/CatalanLocale.res
- src/LocaleStrings/ChineseLocale.res
- src/LocaleStrings/DeutschLocale.res
- src/LocaleStrings/DutchLocale.res
- src/LocaleStrings/EnglishGBLocale.res
- src/LocaleStrings/EnglishLocale.res
- src/LocaleStrings/FrenchBelgiumLocale.res
- src/LocaleStrings/FrenchLocale.res
- src/LocaleStrings/HebrewLocale.res
- src/LocaleStrings/ItalianLocale.res
- src/LocaleStrings/JapaneseLocale.res
- src/LocaleStrings/LocaleStringTypes.res
- src/LocaleStrings/PolishLocale.res
- src/LocaleStrings/PortugueseLocale.res
- src/LocaleStrings/RussianLocale.res
- src/LocaleStrings/SpanishLocale.res
- src/LocaleStrings/SwedishLocale.res
- src/Utilities/DynamicFieldsUtils.res
Added validations for card holder name :- 
- card holder name cannot have digits
Tested via passing card holder name with digits and SDK throws an error
> chore: added validations for card holder name

- src/Payments/PazeTypes.res
- src/Payments/PazeWallet.res
When email is not present with paze. We will send an empty emailAddress so customer can enter it's own email via paze.
Via locally sending empty email address
> chore: added suport for adding email address in paze

- src/Payment.res
- src/Payments/SamsungPayComponent.res
- src/hyper-loader/Elements.res
Added Prod in Samsung Pay always
Via demo store
> chore: added prod env in samsung pay always

- src/Payments/PazeButton.res
Added full screen loader after paze modal gets closed
tested via demo store
> chore: loader after closing paze full screen iframe

- src/CardUtils.res
- src/Components/SavedCardItem.res
- src/Payment.res
Emitting expiry date from the saved card list.
Tested in Hyperswitch-React-Demo-App
> chore: emitting expiry via saved cards screen

- .env
- README.md
- package.json
- src/Payments/CardPayment.res
- webpack.common.js
- webpack.dev.js
set env via jenkins
locally. need to debug in SBX env too.
> chore: add env based var via jenkins

- public/icons/orca.svg
- src/CardSchemeComponent.res
- src/CardUtils.res
Updated the logic to show chevron icon for cardscheme dropdown
@aritro2002 Added  Cartes_Bancaires logo
tested it locally
> refactor: cobaged ux enhancement and added icon for CB

- public/icons/orca.svg
Cartes Bancaires logo was not appearing in firefox.
I have tested on Hyperswitch-React-Demo-App
> fix: cartes bancaires logo not appearing in firefox

- Hyperswitch-React-Demo-App/README.md
- README.md
I tried to get the Hyperswitch React demo app to run locally and couldn't get it to work at first. I then got help from Arun Mishra on Discord. With his help it worked. 
In agreement with Arun, I have tried to add everything I noticed and experienced in the readme and hope to have improved the readme and made it easier to understand for people who are not familiar with the project yet.
Please tell me if something is wrong. I am currently working my way in this project. Thank you very much.
> docs: increase readme for try it local for demo playground

- src/Components/SavedCardItem.res
- src/Components/SavedMethods.res
Removed Dynamic Fields for Saved Card Screen
Locally
> chore: disable dynamic fields for saved card screen

- src/Components/DynamicFields.res
- src/Utilities/DynamicFieldsUtils.res
cards required fields for saved screen fixed
> fix: saved cards screen cards validity issue

- src/Payments/ApplePay.res
Added height support for apple pay button
tested locally
> fix: apple pay height

- src/PaymentElement.res
Click to Pay Loader coming above Saved Cards
https://github.com/user-attachments/assets/101c1c7f-7cca-4b6c-88ae-aa863cc99d40
https://github.com/user-attachments/assets/a82ef5a0-64f8-478a-b6a3-d8b1b4e7418e
> fix: fixed click to pay loader coming above saved cards

- src/Components/DropdownField.res
Inconsistent country code dropdown border
I have checked it by running the local React demo app.
Before:
After:
> fix: inconsistent country code dropdown border

- src/CardPattern.res
- src/CardUtils.res
- src/Payment.res
- src/Payments/CardPayment.res
- src/Utilities/PaymentUtils.res
- src/Utilities/Utils.res
This update enhances our card validation logic by adding regex support for UnionPay and allow card number checking if cardbrand not detected.
The UnionPay regex pattern and pin was derived from the following sources:
1. https://github.com/validatorjs/validator.js/blob/a1e84761802e050ed5d0e3d138e8f87cc1564860/src/lib/isCreditCard.js#L10
2. https://en.wikipedia.org/wiki/Payment_card_number
3. https://www.mystoredemo.io/#/checkout
4. https://m.unionpayintl.com/wap/en/serviceCenter/cardUsingInstructions/1439.shtml
I have checked it by running the local React demo app.
If the card brand is not detected but the card number is valid (passes the Luhn test and falls within the valid card number length range), we allow the user to make a payment. We send `card_network` as `null`.
I have also …
> feat: add regex for UnionPay and allow card number checking if cardbrand not detected

- Dockerfile
Parallel Webpack Compilation and Rescript Build Formation fix Added.
Locally was unable to test. Will add the test result once reviwed.
> chore: docker parallel issue for webpack and rescript

- src/Payments/CardPayment.res
Removed `displaySavedPaymentMethodsCheckbox` check for rendering card Terms 
For rendering terms for cards we are already checking if the payment type is mandate or not, displaySavedPaymentMethodsCheckbox is just an extra frontend check which is unnecessary in this case. 
Tested locally
> refactor: remove displaySavedPaymentMethodsCheckbox condition for card terms

- src/Payment.res
This PR ensures that the card expiry and CVC fields are cleared when switching from the payment section to the saved method section and back.
I have tested in React demo app.
Before:
https://github.com/user-attachments/assets/d6dcbbe7-5d9c-4901-8d86-a20f190da142
After:
https://github.com/user-attachments/assets/c017c7b4-cf86-4d67-b373-ec30c5eb5ded
https://github.com/user-attachments/assets/45d8a0d4-603e-423e-9289-649a2e8f4d96
> fix: clear card expiry and CVC when switching to saved method and back

- src/Components/ClickToPayLearnMore.res
- src/Components/PaymentElementShimmer.res
- src/Components/SavedMethods.res
- src/PaymentElement.res
- src/Types/ClickToPayHelpers.res
Click to Pay Shimmer getting stuck because of the following condition being always true when Click to Pay is enabled
```
savedCardlength === 0 &&
((clickToPayConfig.isReady->Option.isNone &&
loadSavedCards === PaymentType.LoadingSavedCards) || !showFields)
```
1. Click To Pay Disabled
A. Card is saved for both Demo Store and Payment Link
B. Card is not saved for both Demo Store and Payment Link
2. Click To Pay Enabled
A. Card is saved for both Demo Store and Payment Link
B. Card is not saved for both Demo Store and Payment Link
> fix: fixed shimmer stuck for click to pay

- src/Utilities/PaymentBody.res
Added field inside payment_method_data for crypto body.
Previous payload for confirm call in case of no required fields :-
```
payment_method_data : {}
```
New payload for confirm call in case of no required fields :-
```
payment_method_data : { crypto: {} }
```
Tested cases:-
- When no required fields are there
- When required fields are there
> fix: fixed crypto pay body payload

- src/Types/ClickToPayHelpers.res
Changed error handling for Click to Pay. Instead of `Exn.raiseError` which would directly break the flow. I am throwing it in the catch `Exn.anyToExnInternal`
- If click to pay Lib.js breaks, the SDK should not be stuck in loading state
> fix: fixed error handling of click to pay

- src/Components/SurchargeUtils.res
- src/Types/PaymentType.res
Added a prop `customSurchargeMessage` , Merchant can pass a custom string message for showing surcharge details along with a placeholder in the message for populating the currency and amount values from SDK, Placeholder will be `{{amountAndCurrency}}`.
Tested locally :-
- When the message is not passed we fall back to default way of showing surcharge message.
- When the message is passed but the placeholder is not correct then also we fall back to default way.
> chore: custom surcharge message prop exposed

- src/Components/SurchargeUtils.res
- src/LocaleStrings/ArabicLocale.res
- src/LocaleStrings/CatalanLocale.res
- src/LocaleStrings/ChineseLocale.res
- src/LocaleStrings/DeutschLocale.res
- src/LocaleStrings/DutchLocale.res
- src/LocaleStrings/EnglishGBLocale.res
- src/LocaleStrings/EnglishLocale.res
- src/LocaleStrings/FrenchBelgiumLocale.res
- src/LocaleStrings/FrenchLocale.res
- src/LocaleStrings/HebrewLocale.res
- src/LocaleStrings/ItalianLocale.res
- src/LocaleStrings/JapaneseLocale.res
- src/LocaleStrings/LocaleStringTypes.res
- src/LocaleStrings/PolishLocale.res
- src/LocaleStrings/PortugueseLocale.res
- src/LocaleStrings/RussianLocale.res
- src/LocaleStrings/SpanishLocale.res
- src/LocaleStrings/SwedishLocale.res
- src/LocaleStrings/TraditionalChineseLocale.res
- src/Types/PaymentType.res
Exposed a prop `showShortSurchargeMessage`, By default it is false, if it is passed as true then instead of long surcharge message we will show short message.
Format of short surcharge message :-
Fee : Currency amount
Tested locally via passing the prop and with locale support
> chore: short surcharge message prop added

- src/LocaleStrings/LocaleStringHelper.res
- src/hyper-loader/Elements.res
- src/hyper-loader/PaymentMethodsManagementElements.res
Unable to get the default browser language for users running in different locations.
To test it, I changed the default language of my Mac, Firefox, and Chrome to German. After that, I restarted my laptop.
> fix: correction in locale detection

- src/Payments/QRCodeDisplay.res
The QR code model closes, but the "Pay" button remains stuck on "Processing."
I have tested it in react demo app
> fix: fix pay button stuck on processing after QR code modal closes

- cypress-tests/cypress/e2e/cvc-checks-e2e-test.cy.ts
- cypress-tests/cypress/e2e/external-3DS-netcetera-e2e-test.cy.ts
The Netcetera Cypress test was failing because the SDK was taking longer to load, causing the test to execute before the SDK was fully loaded. Additionally, `browserInformation.acceptLanguage` was not set in the dashboard.
I ran cypress test in local React Demo App.
https://github.com/user-attachments/assets/462b4e3b-7e41-4009-a0e1-a83082fd26b5
> fix: netcetera and cvc cypress test

- src/App.res
- src/Redsys3ds.res
- src/ThreeDSAuth.res
- src/Types/PaymentConfirmTypes.res
- src/Utilities/PaymentHelpers.res
- src/Utilities/Utils.res
Redsys 3DS auth implementation.
- handled new next action `invoke_hidden_iframe`
- Task Details:
new next action behavior (`invoke_hidden_iframe`) 
Construct a hidden Iframe as given bellow
endpoint: three_ds_method_url
input field name: method_key
input field value: three_ds_method_data
On submitting, wait for the 10sec time out. If submission of the form takes more than 10secs, call complete_authorize with client_secret and  `threeds_method_comp_ind` flag marked as "N" . Else send `threeds_method_comp_ind` marked as "Y".
`curl --location 'http://localhost:8080/payments/pay_2n5oBH26fEGkdLjsw152/complete_authorize' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'api-key: pk_dev_a4914922937e42f7a55065450b26aa1d' \
--data '{ …
> feat: integration for redsys 3ds

- src/Components/SavedCardItem.res
Added the logic for trimming nickname if the length is greater than 15 characters and append ".." at the end.
Before :-
After :-
Tested it locally
> chore: added logic for trimming nick name for larger length

- src/Utilities/PaymentBody.res
Added Necessary payload in Bancontact confirm body.
` "payment_method_data": {
"bank_redirect": {
"bancontact_card": {}
}
},`
Tested locally via Checking the confirm call and payload
> fix: bancontact confirm payload

- src/Components/DynamicFields.res
- src/Components/PaymentInputField.res
- src/Components/SavedCardItem.res
- src/Payments/BacsBankDebit.res
- src/Payments/Boleto.res
- src/Payments/CardPayment.res
prop unnecessary. component can use config.appearance directly
> refactor: remove appearance prop from various payment components

- src/Components/FullNamePaymentInput.res
The wrong error message is initially shown in the full name input field.
I have tested it in local react demo.
Before:
After:
> fix: fullname input error correction

- src/PaymentOptions.res
This PR adds a class name to the Tab Header element in the payment widget.
-
> chore: add a classname to tab header element

- src/Types/ClickToPayHelpers.res
merchantOrderId length should be less than 50 for passkey authentication
tested locally
> fix: visa CTP passkey auth fix

- Dockerfile.helm
This PR introduces `Dockerfile.helm`, a lightweight Docker image tailored for Helm and CDK-based deployments.
This image builds the Hyperswitch Web SDK using `Node.js` and serves it via a minimal `Nginx` image.
Key Highlights:
Adds a two-stage build process:
- Clones the repo and builds the SDK using Node.js
- Serves the built assets using a minimal Nginx container
Supports dynamic environment variable substitution for:
- `envSdkUrl`
- `envBackendUrl`
- `envLogsUrl`
Image is intended for use in production-like deployments via Helm charts and AWS CDK stacks.
This addition does not affect the existing primary Dockerfile and keeps the deployment concerns separate and modular.
`docker run -p 9050:80 juspaydotin/hyperswitch-web:v0.109.2` …
>  feat: Add lightweight Dockerfile for Helm and CDK-based deployments

- .githooks/commit-msg
- webpack.common.js
Removed CSP headers due to issues with dynamic ACS (Access Control Server) URLs, which were causing payment failures. Since other dynamic or unknown URLs may also be blocked, we are reverting the CSP configuration for now.
CSP will be reintroduced after a thorough audit and verification of all required endpoints and domains to ensure safe and functional integration.
I have tested it in the local react demo app.
https://github.com/user-attachments/assets/1ca8b46a-e9f1-4387-a888-47688839f7f2
> revert: rollback CSP header changes

- src/App.res
- src/Payments/ThreeDSRedirectionModal.res
- src/Types/HyperLoggerTypes.res
- src/Types/PaymentConfirmTypes.res
- src/Utilities/PaymentHelpers.res
New 3DS authentication flow inside a modal dialog in Hyperswitch, Merchants can choose between top level redirection (replacing the current window) and an in-page iframe-based modal, merchants gain better control over UI, faster flows, without leaving the checkout context.
To enable the redirection inside iframe, Merchants need to pass 
`is_iframe_redirection_enabled: true`
with paymentData object for creating paymentIntent.
tested locally
https://github.com/user-attachments/assets/5356b11f-13a7-4a25-80e0-6e76e717cb6c
> feat: 3ds redirection inside popup

- src/Utilities/PaymentHelpers.res
Described in https://github.com/juspay/hyperswitch-web/issues/1041
NA
> fix: use window.top.location.hostname for merchant's domain in sessions call

- src/Payments/CardIframeContainer.res
- src/Payments/CardVault.res
The confirm-intent event listener was not being properly cleaned up, causing it to be attached multiple times. This resulted in multiple confirm-intent calls on subsequent attempts.
Tested Locally
> fix: hs saas cleanup event listener and error messages

- src/Components/SavedMethods.res
The Saved screen shimmer was getting disabled even before we have the saved cards list
Example :- 
https://github.com/user-attachments/assets/39bca6df-0bf1-46fb-8d18-6f0213a483ab
Fixed :-
https://github.com/user-attachments/assets/2594def4-5ab6-452a-a0d6-dcc766fb30fd
Tested Locally
> fix: saved screen shimmer fix

- src/Utilities/APIHelpers/APIUtils.res
Wrong query parameter was set for the retrieve payment intent endpoint — false_sync was used instead of force_sync.
I have tested it locally.
> fix: retrieve payment intent endpoint correction

- .github/workflows/check-linked-issue.yml
I have created issue for checking if any issue is linked with the pr.
Case 1: If no issue is linked
Case 2: If issue is linked
Case 3: If issue is delinked, we rerun the workflow jobs
Case 4: If we relink
> ci: added workflow to check if issue is linked with pr

- src/CardSchemeComponent.res
- src/Hooks/CommonCardProps.res
Previously, the card CVC was cleared only if the previously detected card brand was non-empty. Now, it will be cleared whenever the card brand changes.
https://github.com/user-attachments/assets/030999cb-07cc-49cf-8fce-7ee7cf893b37
> fix: remove CVC number on card brand change & cobadeged cards CVV fixed

- src/Components/PaymentDropDownField.res
- src/Components/PaymentField.res
- src/Components/PaymentInputField.res
- src/Types/ElementType.res
[#1195](https://github.com/juspay/hyperswitch-web/issues/1195)
Previously, only the --invalid class was applied for validation feedback. This update introduces a --valid class, ensuring that both valid and invalid states are now explicitly represented in the UI for inputs and labels.
```
appearance: {
labels: "floating",
rules: {
".Input, .Input:focus, .Input--invalid, .Input--empty": {
border: "none",
boxShadow: "none",
borderRadius: "0",
padding: "0 !important",
// paddingTop: "0 !important",
paddingBottom: "4px !important",
},
".Input, .Input:focus, .Input--empty": {
borderBottom: "1px solid #23366F",
color: "#23366F",
},
".Input--invalid": {
borderBottom: "1px solid #CB4B40 !important",
},
".Label--valid": {
color: "chocolate",
},
".Label": {
marginLeft: "0",
color: "#2167AE", …
```
> feat: add valid class for input and label elements
