src/Utilities/LoggerUtils.res, src/Utilities/PaymentHelpers.res, src/orca-loader/Elements.res
Log redirects in case of confirm error, remove extra logs
=> fix: HS-154: Log redirects in case of confirm error, remove extra logs

src/Components/AccordionContainer.res, src/Types/PaymentType.res
Made max length of accordion items customizable with default 4
=> feat: HS-154: Made max length of accordion items customizable

src/orca-loader/Elements.res, src/orca-log-catcher/OrcaLogger.res
Added debug logs for apple pay
=> feat: HS-154: Added debug logs for apple pay

src/Payments/ApplePay.res, src/orca-loader/Elements.res
**Problem Description -** ApplePay MWeb AB Testing
=> fix: HS-158: AB testing for third party ApplePay

src/Payments/ApplePay.res
**Problem Description -** ApplePay build trigger issue
=> fix: HS-158: ApplePay build trigger

src/Payments/ApplePay.res, src/orca-log-catcher/OrcaLogger.res
OrcaLogger setTimeout intervals changed
=> fix: HS-154: OrcaLogger setTimeout intervals changed

src/Payments/ApplePay.res
Updating the latest AB testing changes to Apple Pay file
=> fix: HS-158: Updated the ApplePay file on main

src/Payments/ApplePay.res
Added loggerState for ApplePay intent and sync
=> fix: HS-154: Added loggerState for ApplePay intent and sync

Hyperswitch-React-Demo-App/public/playgroundIndex.html, Hyperswitch-React-Demo-App/server.js, Hyperswitch-React-Demo-App/src/Payment.js
Invoking loadhyper from script tag and fixed handling the returned instance
=> fix: HS-136: LoadHyper bugfix

src/Payments/ApplePay.res
Reverting ApplePay file to older version for AB testing to evaluate performance diff
=> fix: HS-154: reverting ApplePay file to older version for AB testing

webpack.common.js
=> fix: HS-165: Endpoint changes to non CDN

.gitignore, aws/hyperswitch_web_aws_cleanup_setup.sh, aws/hyperswitch_web_aws_setup.sh
Script added for setup and clean up on AWS standalone deployment
=> feat: HS-169: Script added for setup and clean up on AWS standalone deployment

src/Payments/PaymentMethodsRecord.res, src/Utilities/PaymentBody.res
**Problem Description -** Add Card Redirect Payment Method Type
**Sample Confirm Call -**
```
payment_method: "card_redirect"
payment_method_data: {
card_redirect: {
card_redirect: {}
}
}
payment_method_type: "card_redirect"
```
=> feat: HS-170: Added Card Redirect Payment Method Type

src/GlobalVars.res, src/orca-log-catcher/OrcaLogger.res, webpack.common.js
Added feature flag for logging in webpack
=> feat: HS-172: Added feature flag for logging

src/GlobalVars.res, src/orca-log-catcher/ErrorBoundary.res, src/orca-log-catcher/OrcaLogger.res, webpack.common.js
Conditonal log push based on loggingLevel in webpack
=> feat: HS-172: Conditional log push based on loggingLevel

src/Components/DynamicFields.res, src/Components/SavedMethods.res, src/Payments/CardPayment.res, src/Payments/PaymentMethodsRecord.res
Problem Description - Fixes for Dynamic Fields
Solution - Fixed the following -
1. Removed Card Holder Name from Saved Cards Flow
2. Added additional fields in check for requiredFieldsValid
3. Info Element should be present after the input fields
4. Email field becomes inValid if the payment method is changed
=> fix: HS-132: Fixes for Dynamic Fields

src/Components/DynamicFields.res
**Problem Description -** Country getting changed back to required_field after being updated on payment method changed
=> fix: HS-132: Country fix

Hyperswitch-React-Demo-App/Makefile, Hyperswitch-React-Demo-App/server.js, Hyperswitch-React-Demo-App/webpack.dev.js
problem: endpoint missing for local development 
solution : updated webpack file with the fix
=> fix: HS-333: Fix : fixed endpoint for local development

README.md
=> fix: HS-175: Added external services and brought parity to setup

src/Payments/GPay.res
**Problem Description -** GooglePay Submit callback being called even when the button is not being clicked
=> fix: HS-177: GooglePay submitCallback fix

src/Payments/PaymentMethodsRecord.res, src/Utilities/PaymentBody.res, src/Utilities/PaymentUtils.res
**Payment Method -** reward
**Payment Method Type -** evoucher
**Confirm Body -** 
```
{  payment_method: "reward",
payment_method_data: "reward",
payment_method_type: "evoucher"
}
```
=> feat: HS-182: Added Evoucher Payment Method Type Redirection flow

src/Payments/PaymentMethodsRecord.res
**Problem Description -** If any of the billing detail is empty, render all of the billing details which are coming in the required fields irrespective of whether they are prefilled
**List of Billing Details -**
```
| AddressLine1
| AddressLine2
| AddressCity
| AddressPincode
| AddressState
| AddressCountry(_)
```
=> fix: HS-132: Added all billing details if any is empty

src/Payments/ApplePay.res
**Problem Description -** ApplePay button not rendering via PaymentRequestButton and or Pay using not working with ApplePay
=> fix: HS-185: ApplePay button not rendering and orPayUsing not visible

src/Payments/ApplePay.res, src/Payments/GPay.res
Fixed or pay using check for GooglePay and ApplePay for Bank of America
=> fix: HS-185: Or Pay using fix for GooglePay and ApplePay

.husky/prepare-commit-msg, package.json
**Problem Description -** Husky was not building the code before committing and release rules for patch and chore were not triggering build
=> feat: HS-188: Building before committing and added release rules

src/CardUtils.res, src/Components/DynamicFields.res, src/Components/SavedMethods.res, src/Payment.res, src/Payments/CardPayment.res, src/Payments/PaymentMethodsRecord.res, src/RenderPaymentMethods.res, src/SingleLineCardPayment.res, src/Utilities/DynamicFieldsUtils.res, src/Utilities/PaymentBody.res, src/Utilities/PaymentUtils.res, src/Utilities/RecoilAtoms.res
**Problem Description -** Required support of Dynamic Fields for Bancontact
**Solution -** Moved cards to Dynamic Fields only for Bancontact
=> feat: HS-181: Added support of Dynamic Fields For Bancontact

src/Components/DynamicFields.res, src/Components/Surcharge.res, src/Components/SurchargeUtils.res, src/LocaleString.res, src/Payments/ACHBankTransfer.res, src/Payments/ApplePay.res, src/Payments/BacsBankDebit.res, src/Payments/BacsBankTransfer.res, src/Payments/GPay.res, src/Payments/KlarnaPayment.res, src/Payments/KlarnaSDK.res, src/Payments/PayPal.res, src/Payments/PaymentMethodsRecord.res, src/Payments/PaymentRequestButtonElement.res, src/Payments/PaypalSDK.res, src/Payments/SepaBankTransfer.res, src/Utilities/RecoilAtoms.res, src/Utilities/Utils.res
- Added Surcharge For One Click Wallets
- Added Surcharge For missed payment methods
**Improved UI**
=> feat: HS-148: Added Surcharge for One Click Wallets

src/Payments/QRCodeDisplay.res, src/Utilities/PaymentHelpers.res, src/orca-loader/Elements.res
**Problem Description -** Update Payment Helpers
=> fix: HS-168: Updated Payment Helpers

src/Payments/PaymentMethodsRecord.res, src/Utilities/PaymentBody.res
```
"payment_method": "bank_redirect",
"payment_method_type": "open_banking_uk",
"payment_method_data": {
"bank_redirect": {
"open_banking_uk": {}
}
},
```
=> fix: HS-167: Added Dynamic Fields for Open Banking Uk

src/Components/DynamicFields.res, src/Components/Surcharge.res, src/Payments/PaymentMethodsRecord.res, src/Payments/PaymentMethodsWrapper.res, src/Payments/QRCodeDisplay.res, src/Types/PaymentConfirmTypes.res, src/Utilities/PaymentBody.res, src/Utilities/PaymentHelpers.res, src/Utilities/PaymentUtils.res
**Details -**
```
payment_method - bank_transfer
payment_method_type - pix
```
**Confirm Body -**
```
"payment_method": "bank_transfer",
"payment_method_type": "pix",
"payment_method_data": {
"bank_transfer": {
"pix": {}
}
}
```
=> feat: HS-187: Added Pix Bank Transfer

src/Components/DynamicFields.res
Hypothesis for fixing missing address state in the confirm call
=> fix: HS-2222: Missing Address state

src/Payments/QRCodeDisplay.res, src/Types/PaymentConfirmTypes.res, src/Utilities/PaymentHelpers.res
=> fix: HS-187: Improve UI qr code display for PIX

src/Components/BillingNamePaymentInput.res, src/Components/DynamicFields.res, src/Components/EmailPaymentInput.res, src/Components/FullNamePaymentInput.res, src/Utilities/DynamicFieldsUtils.res, src/Utilities/Utils.res
Error handling for -
- AddressLine1
- AddressLine2
- City
- State
- PostalCode
=> fix: HS-132: Error handling for Address Fields

src/PaymentElement.res
Default Payment Method will always come on top if its there
=> fix: added ordering for saved payment methods

src/Components/PayNowButton.res, src/orca-loader/Hyper.res
fix(PayNowButton): update loader and disable states of pay now button after confirm
=> fix(PayNowButton): update loader and disable states of pay now button after confirm

src/Components/AddressPaymentInput.res, src/Components/DynamicFields.res
Made a hotfix on top of 0.27.2 
merging those changes to this branch
=> fix: hotfix changes for postal code

src/Utilities/ApiEndpoint.res, src/Utilities/ErrorUtils.res, src/orca-loader/Hyper.res
Added pk_dev_ for development purpose testing via local generating publishable keys
=> fix: pk_dev added for development purpose

README.md, package.json
=> docs: updation start:dev

src/Components/NicknamePaymentInput.res, src/Utilities/PaymentHelpers.res, src/orca-loader/Elements.res, src/orca-loader/Hyper.res, src/orca-loader/OrcaUtils.res, src/orca-loader/Types.res
Promise Core Changes for the Core Library use.
=> chore: promise core changes

src/States.json
fix(states): moved states to UM (UnitedStatesMinorOutlyingIslands) out of US
=> fix(states): moved states to UM (UnitedStatesMinorOutlyingIslands)

.github/CODEOWNERS, .github/workflows/pr-label-removal.yml
=> docs: pr-label-changes

src/Components/DropdownField.res, src/Payments/PaymentMethodsRecord.res
=> fix: paypal issue for Ideal Fix

src/Payments/PaymentMethodsRecord.res, src/Utilities/PaymentBody.res
Added new payment method local bank transfer
=> feat: added new redirection payment method local bank transfer

src/Components/SaveDetailsCheckbox.res, src/Components/SavedMethods.res, src/Hooks/UtilityHooks.res, src/Payments/CardPayment.res, src/Payments/PaymentMethodsRecord.res, src/Utilities/PaymentBody.res, src/orca-loader/Hyper.res
Mandate Changes for the Saved card screen & SDK Button Loader changes
Via checking the customer_acceptance is going if we click on Checkbox on the saved cards screen.
=> feat: mandate Changes for the Saved card screen & SDK Button Loader changes

src/orca-loader/Elements.res
Fixed premountloader iframe src
=> fix: updated premountloader iframe src

src/Components/SavedMethods.res
for list.payment_type === NEW_MANDATE the checkbox in mandate will be shown in saved cards
=> feat: normal mandate changes

src/orca-loader/Hyper.res
Whitelist 127.0.0.1 along with localhost for local dev without blocking integration
=> fix: whitelist 127.0.0.1 for local dev

src/orca-log-catcher/OrcaLogger.res
=> fix: priority array to include apple pay logs

src/Utilities/PaymentHelpers.res, src/orca-loader/Elements.res
Retrieve payment intent after the polling is complete for 3ds flow
=> feat: three_ds polling part2

src/orca-loader/Elements.res, src/orca-loader/Types.res, webpack.common.js, webpack.dev.js
Reverting back the CDN changes for preflight of confirm call
=> revert(webpack): reverting back the CDN changes

src/Utilities/PaymentHelpers.res
Added isConfirmCall param in getApiEndpoint() for intentCall
=> fix: cdn confirm endpoint

src/Utilities/PaymentUtils.res
Facing issue maximum depth exceeded
=> fix(paymentutils): fixed Maximum Depth Exceeded

src/States.json
Two states validation was failing throwing invalid state error
=> fix(states): removed few states from the US list

src/Components/DynamicFields.res, src/Payment.res, src/Payments/CardPayment.res, src/Payments/PaymentMethodsRecord.res, src/Utilities/DynamicFieldsUtils.res, src/Utilities/PaymentBody.res
Reverted Card Details, taking card number, card cvc and card expiry from dynamic fields. 
Commits Reverted -
1. 1b92d4487787f7c95aaddee589755277a7b2cdf3
2. b5ce1c14fa5ca2b5aceca47d7070876656ebf7ba
=> Fix: revert card details

package.json
=> Fix: creating a new tag 0.50.7

src/Components/PaymentDropDownField.res
Fix for - Dropdown validation error even when the first option is preselected
=> fix: dropdown error even when first option is selected

src/BrowserSpec.res, src/Components/SavedMethods.res, src/Payments/ApplePay.res, src/Payments/CardPayment.res, src/Payments/GPay.res, src/Utilities/PaymentBody.res, src/Utilities/PaymentHelpers.res, src/Utilities/Utils.res, src/orca-loader/Elements.res, src/orca-loader/Hyper.res, src/orca-loader/PaymentSessionMethods.res
Added utility function
Code compilation
=> fix: added utility function

src/Payments/PreMountLoader.res, src/orca-loader/Elements.res
Reverts juspay/hyperswitch-web#367
=> revert: do not unmount preMountLoader iframe

src/Utilities/PaymentHelpers.res, src/Utilities/Utils.res
Updated headers
Passing headers
=> fix: updated headers

package.json
added patch for revert to generate tag
Cannot be tested
=> fix: added patch for revert to generate tag

src/Components/SavedMethods.res
Extra check has been added for showing checkbox in the Saved PM
=> fix: saved method checkbox condition updated

src/Payments/PaymentMethodsRecord.res, src/Utilities/PaymentBody.res
Enabled afterpay using dynamic fields
=> feat: enabled afterpay with dynamic fields

src/Utilities/PaymentBody.res
Afterpay body empty if required fields are empty
=> fix: afterpay_body fix

src/CardUtils.res, src/Components/SurchargeUtils.res, src/LoaderController.res, src/PaymentElement.res, src/Payments/ApplePay.res, src/Payments/GPay.res, src/Payments/KlarnaSDK.res, src/Payments/KlarnaSDKTypes.res, src/Payments/PayPal.res, src/Payments/PaymentRequestButtonElement.res, src/Payments/PaypalSDK.res, src/RenderPaymentMethods.res, src/Types/CardThemeType.res, src/Types/PaymentModeType.res, src/Types/PaymentType.res, src/Utilities/DynamicFieldsUtils.res, src/Utilities/PaymentUtils.res, src/Utilities/RecoilAtoms.res, src/Utilities/Utils.res, src/WalletElement.res, src/orca-loader/Elements.res
Added Klarna as a one click widget
Test Klarna SDK flow and Klarna Redirect
=> feat: added Klarna as a one click widget

src/orca-loader/Hyper.res
=> fix: redirect issue

Hyperswitch-React-Demo-App/server.js
HYPERSWITCH_SERVER_URL_FOR_DEMO_APP key added for docker demo app setup
via passing these values from env - HYPERSWITCH_SERVER_URL_FOR_DEMO_APP
=> fix: demo app docker url needed

src/Payments/ApplePay.res, src/Payments/GPay.res, src/Payments/PayPal.res, src/Types/PaymentType.res
Added button border radius customize for wallets 
Via passing - 
```
wallets: {
...,
style: {
...,
buttonRadius: 50,
},
},
```
=> fix: button border changes

src/orca-loader/PaymentSessionMethods.res, src/orca-loader/Types.res
`confirmWithLastUsedPaymentMethod` & `getCustomerLastUsedPaymentMethodData` these 2 headless functions added.
Via headless function integration.
=> feat: added confirm and get handler for last used payment

Hyperswitch-React-Demo-App/webpack.dev.js
This PR enables the React demo app to listen on the `0.0.0.0` IP address. This is done to allow running the demo app within Docker containers.
Docker Compose setup on the `juspay/hyperswitch` repository.
=> chore(Hyperswitch-React-Demo-App): specify `host` as `0.0.0.0` for development server

src/Components/DynamicFields.res, src/LocaleStrings/ArabicLocale.res, src/LocaleStrings/CatalanLocale.res, src/LocaleStrings/DeutschLocale.res, src/LocaleStrings/DutchLocale.res, src/LocaleStrings/EnglishGBLocale.res, src/LocaleStrings/EnglishLocale.res, src/LocaleStrings/FrenchBelgiumLocale.res, src/LocaleStrings/FrenchLocale.res, src/LocaleStrings/HebrewLocale.res, src/LocaleStrings/ItalianLocale.res, src/LocaleStrings/JapaneseLocale.res, src/LocaleStrings/LocaleStringTypes.res, src/LocaleStrings/PolishLocale.res, src/LocaleStrings/PortugueseLocale.res, src/LocaleStrings/RussianLocale.res, src/LocaleStrings/SpanishLocale.res, src/LocaleStrings/SwedishLocale.res, src/Payments/CardPayment.res, src/RenderPaymentMethods.res, src/SingleLineCardPayment.res
=> fix: locales update for mm/yy

src/orca-loader/PaymentSessionMethods.res
Compare logic redundant removal
=> refactor: redundant code removal

src/Payments/CardPayment.res, src/Types/PaymentType.res
`hideCardNicknameField` added
Via passing the prop
=> feat: hideCardNicknameField added

src/Components/SavedMethods.res, src/PaymentElement.res, src/Utilities/ApplePayHelpers.res, src/Utilities/GooglePayHelpers.res, src/Utilities/PaymentHelpers.res
Fixed ApplePay and GooglePay Saved Methods Flow
=> fix: fixed Saved Methods ApplePay and GooglePay Handler

src/orca-loader/PaymentSessionMethods.res
Handling google pay throwing error edge case
=> fix: google Pay Fix

src/Utilities/Utils.res
Temp fix - will revert back to the original.
=> fix: browser name changes - temp

.github/CODEOWNERS
=> fix: codeowner changes

src/ThreeDSMethod.res
Fixed Netcetra 3ds not opening and added fallback log
Tested 3ds authentication
=> fix: fixed netcetra 3ds not opening and added fallback log

src/Payments/PreMountLoader.res
PaymentLoader was not getting unmounted this is the fix.
Via making in mount unmount again via demo store
=> fix: premount loader fix

src/LoaderController.res, src/orca-loader/LoaderPaymentElement.res
Removed Pragma Marks from Files that not needed more.
=> chore: remove pragma marks from file that not needed

src/LocaleStrings/ArabicLocale.res, src/LocaleStrings/CatalanLocale.res, src/LocaleStrings/DeutschLocale.res, src/LocaleStrings/DutchLocale.res, src/LocaleStrings/EnglishGBLocale.res, src/LocaleStrings/EnglishLocale.res, src/LocaleStrings/FrenchBelgiumLocale.res, src/LocaleStrings/FrenchLocale.res, src/LocaleStrings/HebrewLocale.res, src/LocaleStrings/ItalianLocale.res, src/LocaleStrings/JapaneseLocale.res, src/LocaleStrings/LocaleStringTypes.res, src/LocaleStrings/PolishLocale.res, src/LocaleStrings/PortugueseLocale.res, src/LocaleStrings/RussianLocale.res, src/LocaleStrings/SpanishLocale.res, src/LocaleStrings/SwedishLocale.res, src/Payments/DateOfBirth.res
Without clicking the Date menu the error was comin\g & Added locale support
Via opening the SDK.
=> fix: error string

src/CollectWidget.res, src/PaymentMethodCollectElement.res, src/Types/PaymentMethodCollectTypes.res, src/Utilities/PaymentMethodCollectUtils.res, src/Utilities/Utils.res
=> refactor(payout): make BIC optional for SEPA txns

src/Payments/ACHBankDebit.res, src/Utilities/PaymentBody.res
Customer Acceptance was not getting passed for the bank debits.
Via checking the confirm Call body
=> fix: customer acceptance issue for bank debits

src/Components/DynamicFields.res, src/Components/PixPaymentInput.res, src/Payments/PaymentMethodsRecord.res, src/Utilities/DynamicFieldsUtils.res, src/Utilities/RecoilAtoms.res
Added new fields required in the API contract changes for Pix(Itaubank)
configured pix connector and rendered sdk using the respective api keys
=> feat: pix-ItauBank api contract changes

src/Payment.res, src/Utilities/PaymentUtils.res
=> refactor: payments code refactor

src/Components/SavedMethods.res, tailwind.config.js
Fixed the double scroll bar issue in firefox
by rendering the sdk in firefox and checking
=> fix: double scroll bar fix

src/Window.res
Reverting - refactor: handle redirections for iframed content (https://github.com/juspay/hyperswitch-web/pull/557)
Redirection should happen inside the iframe and not on the top level
=> revert: handle redirections for iframed content (#557)

.github/CODEOWNERS
=> docs: updated code owners

src/CardSchemeComponent.res, src/CardUtils.res, src/Components/DynamicFields.res, src/Components/PaymentInputField.res, src/Payment.res, src/Payments/CardPayment.res, src/RenderPaymentMethods.res, src/SingleLineCardPayment.res, src/Utilities/RecoilAtoms.res
Added support to process co badged cards
Tested it locally on sandbox
=> feat: added support for cobadged cards

Hyperswitch-React-Demo-App/package.json, package-lock.json, package.json
Dependant Bot Alerts fix.
Via Code compile and basic sanity
=> fix: dependant bot alerts

src/Components/DynamicFields.res
=> refactor: removed unused variable

package-lock.json, package.json
Reverts juspay/hyperswitch-web#717
=> Revert "chore(deps): bump @sentry/browser and @sentry/react"

.github/workflows/run-automation-test.yml, cypress-tests/cypress/support/utils.ts
=> fix: workflow indentation fix

.github/workflows/run-automation-test.yml
=> fix: cypress env fix

src/BubblegumTheme.res, src/CardTheme.res, src/Types/CardThemeType.res
This is the bubblegum theme of stripe
This is how our sdk looks
=> feat: added bubblegum theme

webpack.common.js
Now we will move to `web/${version}/${majorversion}` path in S3
via pushing to s3
=> fix: web package added

src/LoaderController.res, src/Payments/PaypalSDK.res, src/Payments/PaypalSDKHelpers.res, src/Utilities/PaymentHelpers.res, src/Utilities/RecoilAtoms.res, src/Utilities/Utils.res, src/orca-loader/Elements.res, src/orca-loader/LoaderPaymentElement.res, src/orca-loader/Types.res
=> feat: added confirm handler

src/Payments/PaypalSDK.res, src/Payments/PaypalSDKHelpers.res, src/Types/ApplePayTypes.res, src/Types/PaypalSDKTypes.res, src/Utilities/ApplePayHelpers.res, src/Utilities/PaymentHelpers.res, src/Utilities/TaxCalculation.res
Added onShippingAddressChange event listeners to track whether there is change in shipping address, and did tax calculation based on address
=> feat: dynamic tax calculation in paypal

src/index.css
I removed the changes I made in PR #746 since they were not working.
=> revert: remove changes of pr #746

src/orca-loader/Elements.res
Google Pay Unified checkout fix
=> fix: Gpay unified checkout fix

src/Utilities/Utils.res
=> refactor: fetch api changes

src/Payments/ACHBankTransfer.res, src/Payments/PaymentMethodsRecord.res, src/Utilities/PaymentBody.res
Added dynamic fields for ach bank transfer
Tested via passing the values in required fields and then checking which fields are getting rendered
=> chore: added dynamic fields for ach

src/Utilities/DynamicFieldsUtils.res
Added dynamic fields support for Walley
=> chore: add dynamic fields support for walley

src/Utilities/DynamicFieldsUtils.res
Enabled dynamic fields for pay bright payment method
=> chore: enabled dynamic fields for pay bright

src/Payments/PaymentMethodsRecord.res, src/Utilities/DynamicFieldsUtils.res, src/Utilities/PaymentBody.res
Enabled dynamic fields for multibanco bank transfer payment method
=> chore: enabled dynamic fields for multibanco bank transfer

src/Components/SavedCardItem.res, src/LocaleStrings/ChineseLocale.res
Changed CVC to security code for chinese (zh) locale.
Tested via passing locale as zh and rendering the SDK.
=> refactor: changed cvc to security code

src/Components/DynamicFields.res
Card holder name was coming intermittently, fixed by adding an additional dependency
=> fix: card holder name

src/Components/DynamicFields.res, src/Payments/BankDebitModal.res, src/Payments/CardPayment.res
Adjusted some styles and paddings
=> style: minor ui styling

src/Payments/CardPayment.res
Added a post message to the merchant for expiry date validations
checked via accepting the message in checkoutform.js
=> chore: sent a post message for expiry date

src/Payments/PazeWallet.res
=> chore: removed console logs

src/Payments/PaymentMethodsWrapper.res, src/Utilities/DynamicFieldsUtils.res
Made a fix for confirm call in crypto payment method
tested via configuring crypto payment method and checking confirm call
=> fix: crypto currency payment method

src/Utilities/PaymentHelpers.res
Added payment id in query params for return url in redirection flows
tested via checking redirection flow and payment_id is getting appended
=> chore: added payment id in query params

src/Payment.res, src/Payments/CardPayment.res
Moved the expiry date message to on change of expiry field
tested through demo store via checking expiry validations
=> refactor: moved the expiry message to on change

src/PaymentElement.res, src/Utilities/PaymentUtils.res
By making network throttling variable
=> fix: show card form by default rendering issue

src/LocaleStrings/ChineseLocale.res
Chinese Locale - Card Number label value change.
Via local
=> chore: cardNumberLabel change for zh - locale

src/Hooks/UtilityHooks.res, src/Payments/CardPayment.res
Hypothesis that this is causing issue of not re-rendering this.
Will test via Payment Links
=> fix: re render issue of card nickname

src/Hooks/UtilityHooks.res, src/Payments/CardPayment.res
Reverts juspay/hyperswitch-web#823
=> Revert "fix: re render issue of card nickname"

src/CardUtils.res
=> fix: card validation focus check

src/Utilities/DynamicFieldsUtils.res
Passing last name with spaces if it has multiple spaces in the name.
Locally passing card holder name.
=> chore: appending last name with spaces

src/Components/DynamicFields.res, src/Components/SavedCardItem.res, src/Components/SavedMethods.res, src/PaymentElement.res
…updation
Saved method screen visibility and dynamic fields value setting 
tested locally
=> fix: display saved method screen condition and dynamic fields values updation issue in saved card screen

webpack.common.js
Update API Endpoints for Integration, Sandbox, and Production Environments
Tested locally in demo store
=> chore: update confirm/backend endpoints

src/Payments/PaymentMethodsRecord.res
changed logo for cash to code e-voucher payment method
Previous:-
Current:-
tested locally
=> chore: cash to code e voucher logo changed

src/Utilities/PaymentUtils.res
Reverted changes for klarna checkout sdk 
Locally
=> revert: reverting some changes for klarna checkout

src/hyper-loader/Elements.res
[Previous PR](https://github.com/juspay/hyperswitch-web/pull/519)
=> fix: added initiative context back for trustpay applepay

src/Components/SaveDetailsCheckbox.res
Fixed:
Before:-
After:-
Locally
=> fix: checkbox margin issue

package-lock.json, src/LoaderController.res, src/PaymentMethodCollectElement.res, src/Payments/ApplePay.res, src/Payments/PayPal.res, src/Payments/PaypalSDKHelpers.res, src/Utilities/PaymentHelpers.res, src/hyper-loader/Elements.res, src/hyper-loader/Hyper.res, src/hyper-loader/LoaderPaymentElement.res, src/hyper-loader/PaymentMethodsManagementElements.res, src/hyper-loader/PaymentSessionMethods.res
=> fix: add catch block

src/Utilities/Utils.res, src/Window.res
=> fix: get attribute type fixed for handling null values

src/States.json
Added new country state mapping
Local file updation only
=> refactor: state.json file updated

src/Components/SavedMethods.res
Saved card screen shimmer loading condition fixed
tested locally
=> fix: shimmer fixed for saved flow

.eslintrc.json, src/PaymentMethodCollectElement.res, src/Payments/BecsBankDebit.res, src/Payments/PazeWallet.res, src/Payments/QRCodeDisplay.res, src/Types/ClickToPayHelpers.res, src/Utilities/ApplePayHelpers.res, src/Utilities/PaymentHelpers.res, src/Utilities/Utils.res, src/hyper-loader/Elements.res, src/hyper-loader/Hyper.res, src/hyper-loader/LoaderPaymentElement.res, src/hyper-log-catcher/Sentry.res
=> chore(eslint): enforce no console logs in codebase

src/BubblegumTheme.res, src/FormViewJourney.res, src/Hooks/CommonHooks.res, src/Types/PaypalSDKTypes.res, src/Types/SessionsType.res, src/Utilities/PaymentBody.res, src/hyper-loader/PaymentSessionMethods.res
=> refactor: formated main branch code

src/Components/SavedCardItem.res
Fixed Responsive Behaviour for Saved Cards
=> fix: Fixed Responsive Behaviour for Saved Cards

src/App.res
Minor refactor - Added open card utils
tested via running demo app locally
=> refactor: minor refactor

src/Bank.res
Below banks are added to FPX bank list
- Bank Islam
- Bank Of China
Verified locally using payment links
=> chore: update FPX bank list

src/Components/SavedCardItem.res
Fixed the scenario when Billing Details are missing
=> fix: fix: Missing Billing Details

src/LoaderController.res
Reverts juspay/hyperswitch-web#941
=> revert: detect country correction

public/build.html
Added counter to track how many times sdk is opened
I have tested in local react demo app.
=> chore: counter to track how many times sdk is opened

src/hyper-loader/Hyper.res
When we used to have multiple instance of HyperLoader initiated with different publishable key then publishable key was not getting updated in our Hyper.make. 
Connected my local hyperloader with local dashboard to replicate and solve the issue.
=> fix: HyperLoader Reinitialisation

src/hyper-loader/Elements.res
Added logs In case when Connector value is not found for Trustpay apple pay and google pay flow.
=> refactor: added logs in trustpay wallets flow

package-lock.json, src/hyper-log-catcher/Sentry.res
just removed the sentry scope and replaced with import sentry
Locally
=> fix(sentry): fix sentry integrations

src/PaymentElement.res, src/WalletElement.res, src/hyper-log-catcher/ErrorBoundary.res, src/hyper-log-catcher/ReusableReactSuspense.res
Added publishable key to crash logs, to help the team debug better
Tested it locally
=> refactor: added pk to crash logs

src/Components/InfoElement.res, src/PaymentDetails.res, src/PaymentElement.res, src/Payments/InstantBankTransfer.res, src/Payments/InstantBankTransferLazy.res, src/Payments/PaymentMethodsRecord.res, src/Types/PaymentModeType.res, src/Utilities/DynamicFieldsUtils.res, src/Utilities/PaymentBody.res, src/Utilities/PaymentUtils.res
- Added Instant Bank Transfer Payment Method
- Added support for payment method type as "sepa_bank_transfer" instead of "sepa"
Tested via Integ :-
https://github.com/user-attachments/assets/a1fe06b1-5c0c-42c6-a17b-7bed30cb341b
=> feat: added instant bank transfer method

webpack.common.js
I have added localhost sources to csp.
=> chore: add localhost sources to csp

src/PaymentElement.res
I have added new rule for payment-label. We can use it to customise `paymentMethodsHeaderText` and `savedPaymentMethodsHeaderText` using class `.PaymentLabel`.
I have tested it in local react demo app.
https://github.com/user-attachments/assets/32c6f70b-d1fa-46d1-a8a5-406c1f72210f
Modifications in `Payment.js`
```
<HyperElements
hyper={hyperPromise}
options={{
clientSecret: isCypressTestMode
? clientSecretQueryParam
: clientSecret,
appearance: {
labels: "floating",
variables: {
colorIconCardCvcError: "#CB4B40",
// spacingUnit: "16px",
},
rules: {
".Input, .Input:focus, .Input--invalid, .Input--empty": {
border: "none",
boxShadow: "none",
borderRadius: "28px",
// padding: "0 !important",
// paddingBottom: "4px !important",
// borderColor: " #23366F",
paddingLeft: "22px !important", …
```
=> chore: add new css rule for payment-label

Hyperswitch-React-Demo-App/src/CheckoutForm.js, cypress-tests/cypress/e2e/cvc-checks-e2e-test.cy.ts
=> test: correction in test case, user can enter 4 digit cvc on saved payment methods screen

src/Utilities/Utils.res
Fixed bubblegum theme flow.
I have tested in local react demo store.
=> fix: bubblegum theme correction

.github/workflows/calendar-version.yml
=> ci: release calendar version

.github/workflows/calendar-version.yml
=> ci: update package json version

.github/workflows/calendar-version.yml
=> ci: update package.json version

.github/workflows/calendar-version.yml
=> ci: update verified tag

src/Redsys3ds.res, webpack.common.js
=> fix: added redsys3ds frame source in webpack

docs/SCRIPT_INVENTORY.md
Added missing loaded scripts in security inventory docs.
I used vs code preview tool to test it.
=> docs: add missing loaded scripts in security inventory docs

webpack.common.js
I'm allowing all `https:` URLs in the `frame-src` directive because the ACH URLs are dynamic and can vary.
I have tested it in local react demo app.
=> fix: csp correction

cypress-tests/cypress/e2e/mifinity-flow-test.cy.ts, cypress-tests/cypress/support/utils.ts, src/Utilities/TestUtils.res
I have added a test case for Mifinity payment flow.
I have tested in local cypress.
https://github.com/user-attachments/assets/8c4a742a-5ec0-41c3-932e-37e167dfe77e
=> test: mifinity payment flow

cypress-tests/cypress/e2e/crpto-flow-test.cy.ts, cypress-tests/cypress/support/utils.ts
I have added a test case for Crypto payment flow.
I have tested it in local cypress test.
https://github.com/user-attachments/assets/6fda5662-6531-4ead-9156-5360a1219116
=> test: crypto payment flow

src/Utilities/PaymentBody.res
Changed the `encypted_payload` to `encrypted_payload`
Reference PR - https://github.com/juspay/hyperswitch/pull/8063
=> fix: encrypted payload fixed

cypress-tests/cypress/e2e/redsys-3ds-flow-test.cy.ts, cypress-tests/cypress/support/cards.ts
Added cypress tests for Redsys 3DS flow
Tested locally
=> test(cypress): redsys 3ds flow test

src/Components/DynamicFields.res, src/Types/ClickToPayHelpers.res, src/Utilities/DynamicFieldsUtils.res
Added phoneNumber and fullName field for add card with visa CTP
locally tested
=> fix: fullName and phoneNumber is required to add card with visa CTP

src/hyper-log-catcher/Sentry.res
I have added environment option in sentry config to differentiate between production and development logs.
=> chore: add environment in sentry

src/RenderPaymentMethods.res
I have added css rule in payment method container.
I have tested it in local react demo app.
Used below css rules
Before:
After:
https://github.com/user-attachments/assets/341eabb0-8061-4e3f-8468-02befb7f7caa
=> chore: add css rule in payment method container

package.json
I have added git submodule initialization to postinstall script.
I have tested it in local react demo app.
=> chore: add git submodule initialization to postinstall script

webpack.common.js
I have added csp for klarna pop up flow.
https://github.com/user-attachments/assets/e632f539-f6ae-43f9-a720-8471ee4a8969
=> chore: add csp for another klarna flow

src/LocaleStrings/ArabicLocale.res, src/LocaleStrings/CatalanLocale.res, src/LocaleStrings/ChineseLocale.res, src/LocaleStrings/DeutschLocale.res, src/LocaleStrings/DutchLocale.res, src/LocaleStrings/EnglishGBLocale.res, src/LocaleStrings/EnglishLocale.res, src/LocaleStrings/FrenchBelgiumLocale.res, src/LocaleStrings/FrenchLocale.res, src/LocaleStrings/HebrewLocale.res, src/LocaleStrings/ItalianLocale.res, src/LocaleStrings/JapaneseLocale.res, src/LocaleStrings/LocaleStringTypes.res, src/LocaleStrings/PolishLocale.res, src/LocaleStrings/PortugueseLocale.res, src/LocaleStrings/RussianLocale.res, src/LocaleStrings/SpanishLocale.res, src/LocaleStrings/SwedishLocale.res, src/LocaleStrings/TraditionalChineseLocale.res
Added new locales for Pix payment method dynamic fields
=> chore: added locale for pix new dynamic fields

src/Payments/PreMountLoader.res, src/Utilities/APIHelpers/APIUtils.res, src/Utilities/PaymentHelpers.res, src/Utilities/Utils.res, src/hyper-loader/PaymentSessionMethods.res, src/hyper-log-catcher/LogAPIResponse.res
Refactored Customer Payment Method List
Tested locally API working fine.
=> chore: refactor customer payment method list

src/Payments/GPay.res, src/Payments/PaypalSDK.res, src/Payments/PlaidSDKIframe.res, src/Types/HyperLoggerTypes.res, src/Utilities/ApplePayHelpers.res, src/Utilities/LoggerUtils.res, src/Utilities/PaymentHelpers.res, src/Utilities/PaymentHelpersV2.res, src/hyper-loader/Elements.res, src/hyper-loader/Hyper.res, src/hyper-log-catcher/ErrorBoundary.res, src/hyper-log-catcher/HyperLogger.res
=> fix: logs payload fixed

Hyperswitch-React-Demo-App/src/CheckoutForm.js, package-lock.json, package.json
=> chore: update package json

src/Utilities/APIHelpers/APIUtils.res, src/Utilities/PaymentHelpers.res, src/Utilities/TaxCalculation.res
I have refactored calculate tax function.
I have tested it locally.
=> refactor: calculate tax

.github/workflows/conventional-commit-check.yml
Conventional commit message check was taking more time than  expected used simple JS to execute
Via running local runners
=> ci: conventional commit message check

src/Payments/CardPayment.res, src/Payments/CardVault.res
Fixed condition for token
Tested locally
=> fix: token retrieval fix and margin

.github/workflows/pr-label-removal.yml
=> ci: pr-label-removal

src/Utilities/PaymentHelpers.res
Confirm Intent call based upon V2 PML State
Tested Locally
=> fix: v2 confirm intent call

Hyperswitch-React-Demo-App/server.js, Hyperswitch-React-Demo-App/src/App.js, Hyperswitch-React-Demo-App/src/index.js, Hyperswitch-React-Demo-App/webpack.common.js
Remove warning from the browser console
Checked the console warning removed.
=> fix: warning remove

src/Country.res
Added `Asia/Calcutta` as a timezone mapping
Tested Locally
=> fix: added new timezone in local country mappings

.github/workflows/check-linked-issue.yml
Time improvement and extracting out necessary things out from the Github API
Via Github runners
=> chore: link issue pipeline time reduce

.github/workflows/auto-assign.yml
Added action for auto assign
Via Github runners
=> ci: auto assign

.github/workflows/check-linked-issue.yml, .github/workflows/manual-release.yml, .github/workflows/stable-release.yml
I have created a workflow for manual release.
I have checked it by creating a private repo under the Juspay organization.
case 1: using auto version bumping
https://github.com/user-attachments/assets/e6f7667d-2014-4db3-b8d7-79c41372f67a
case 2: using manual version bumping (empty)
case 3: using manual version bumping (lesser than current)
case 4: non admin user
=> ci: added workflow for stable release

src/Payments/PaymentMethodsRecord.res, src/Utilities/DynamicFieldsUtils.res
Added Upi Intent payment method
tested locally
=> feat: added upi intent qr flow  payment method

src/Utilities/PaymentBodyV2.res, src/Utilities/PaymentUtilsV2.res
=> fix: unnecessary warnings removed

src/Components/DynamicFields.res, src/Components/PixPaymentInput.res, src/LocaleStrings/ArabicLocale.res, src/LocaleStrings/CatalanLocale.res, src/LocaleStrings/ChineseLocale.res, src/LocaleStrings/DeutschLocale.res, src/LocaleStrings/DutchLocale.res, src/LocaleStrings/EnglishGBLocale.res, src/LocaleStrings/EnglishLocale.res, src/LocaleStrings/FrenchBelgiumLocale.res, src/LocaleStrings/FrenchLocale.res, src/LocaleStrings/HebrewLocale.res, src/LocaleStrings/ItalianLocale.res, src/LocaleStrings/JapaneseLocale.res, src/LocaleStrings/LocaleStringTypes.res, src/LocaleStrings/PolishLocale.res, src/LocaleStrings/PortugueseLocale.res, src/LocaleStrings/RussianLocale.res, src/LocaleStrings/SpanishLocale.res, src/LocaleStrings/SwedishLocale.res, src/LocaleStrings/TraditionalChineseLocale.res, src/Payments/PaymentMethodsRecord.res, src/Utilities/DynamicFieldsUtils.res, src/Utilities/RecoilAtoms.res
Removed destination bank account id from dynamic fields
tested locally
=> refactor: removed destination bank account id from dynamic fields

src/Utilities/PaymentBody.res
Fixed Bluecode payment method confirm request payload
#1176
=> fix: bluecode payment method body fix

src/LocaleStrings/CatalanLocale.res, src/LocaleStrings/DeutschLocale.res, src/LocaleStrings/DutchLocale.res, src/LocaleStrings/EnglishGBLocale.res, src/LocaleStrings/EnglishLocale.res, src/LocaleStrings/FrenchBelgiumLocale.res, src/LocaleStrings/FrenchLocale.res, src/LocaleStrings/ItalianLocale.res, src/LocaleStrings/PolishLocale.res, src/LocaleStrings/PortugueseLocale.res, src/LocaleStrings/RussianLocale.res, src/LocaleStrings/SpanishLocale.res, src/LocaleStrings/SwedishLocale.res
Renamed Ali Pay HK payment method to AlipayHK and Ali Pay to Alipay
#1192
=> refactor: renamed ali pay hk payment method to AlipayHK and Ali Pay to Alipay

Dockerfile
DockerFile submodule issue
#1201 
Running locally via Docker compose
=> fix: DockerFile

cypress-tests/cypress/e2e/cashtocode-evoucher-e2e-test.cy.ts, cypress-tests/cypress/e2e/cashtocode-voucher-e2e-test.cy.ts, cypress-tests/cypress/support/utils.ts
=> test: added cashtocode test cases

src/LocaleStrings/ArabicLocale.res, src/LocaleStrings/CatalanLocale.res, src/LocaleStrings/ChineseLocale.res, src/LocaleStrings/DeutschLocale.res, src/LocaleStrings/DutchLocale.res, src/LocaleStrings/EnglishGBLocale.res, src/LocaleStrings/EnglishLocale.res, src/LocaleStrings/FrenchBelgiumLocale.res, src/LocaleStrings/FrenchLocale.res, src/LocaleStrings/HebrewLocale.res, src/LocaleStrings/ItalianLocale.res, src/LocaleStrings/JapaneseLocale.res, src/LocaleStrings/LocaleStringTypes.res, src/LocaleStrings/PolishLocale.res, src/LocaleStrings/PortugueseLocale.res, src/LocaleStrings/RussianLocale.res, src/LocaleStrings/SpanishLocale.res, src/LocaleStrings/SwedishLocale.res, src/LocaleStrings/TraditionalChineseLocale.res, src/Utilities/PaymentMethodCollectUtils.res
Added validation for BACS.
https://github.com/user-attachments/assets/7ca179b0-4609-4899-a6c5-1c654853a861
=> fix: add validation for bacs
